const obj={
    c1:"https://www.salesforce.com/",
    c2:"https://www.hubspot.com/",
    c3:"https://www.activecampaign.com/",
    c4:"https://setshape.com/",
    c5:"https://www.zoho.com/",
    c6:"https://www.freshworks.com/",
    c7:"https://www.pipedrive.com/",
    c8:"https://sharpspring.com/",
    c9:"https://www.copper.com/",
    c10:"https://keap.com/",
    c11:"https://www.thryv.com/",
    c12:"https://www.pipelinersales.com/",
    c13:"https://clickup.com/",
    c14:"https://www.lessannoyingcrm.com/",
    c15:"https://www.nimble.com/",
    c16:"https://www.close.com/",
    c17:"https://www.nextiva.com/",
    c18:"https://www.insightly.com/",
    c19:"https://www.salesforce.com/",
    c20:"https://mypipeline.co.in/",




    c21:"https://www.vendasta.com/",
    c22:"https://dynamics.microsoft.com/",
    c23:"https://www.nutshell.com/",
    c24:"https://www.zendesk.com/",
    c25:"https://www.wrike.com/",
    c26:"https://edrone.me/",
    c27:"https://www.creatio.com/",
    c28:"https://salesflare.com/",
    c29:"https://nethunt.com/",
    c30:"https://1channel.ai/",
    c31:"https://www.accelo.com/",
    c32:"https://www.engagebay.com/",
    c33:"https://www.streak.tech/",
    c34:"https://www.flowlu.com/",
    c35:"https://www.vtiger.com/",
    c36:"https://www.prospectsoft.com/",
    c37:"https://solidperformers.com/",
    c38:"https://www.scoro.com/",
    c39:"https://spiro.ai/",
    c40:"https://www.leadsquared.com/",


    c41:"https://monday.com/",
    c42:"https://www.epromis.com/",
    c43:"https://www.method.me/",
    c44:"https://setshape.com/",
    c45:"https://www.membrain.com/",
    c46:"https://www.sugarcrm.com/",
    c47:"https://www.deskera.com/",
    c48:"https://www.lime-technologies.com/",
    c49:"https://capsulecrm.com/",
    c50:"https://www.benchmarkone.com/",
    c51:"https://www.clearc2.com/",
    c52:"https://www.workbooks.com/",
    c53:"https://daylitemac.com/",
    c54:"https://www.onehash.ai/",
    c55:"https://www.vbout.com/",
    c56:"https://dubb.com/",
    c57:"https://www.salezshark.com/",
    c58:"https://www.upsales.com/",
    c59:"https://www.netsuite.com/",
    c60:"https://www.oracle.com/",

 
    c61:"https://freeagentcrm.com/",
    c62:"https://www.bitrix24.in/?redirect_from=www.bitrix24.com%",
    c63:"https://www.onepagecrm.com/",
    c64:"https://www.reallysimplesystems.com/",
    c65:"https://ontraport.com/",
    c66:"https://www.apptivo.com/",
    c67:"https://www.vcita.com/",
    c68:"https://www.bigcontacts.com/",
    c69:"https://www.salesmate.io/",
    c70:"https://www.lime-technologies.com/",
    c71:"https://simply-crm.com/",
    c72:"https://www.kapturecrm.com/",
    c73:"https://snov.io/",
    c74:"https://www.interspire.com/",
    c75:"https://orgzit.com/",
    c76:"https://allclients.com/",
    c77:"https://claritysoft.com/",
    c78:"https://companyhub.com/",
    c79:"https://www.zendesk.com/",
    c80:"https://www.jarviscrm.com/",
    c81:"https://www.referrizer.com/",
    c82:"https://www.convergehub.com/",
    c83:"https://elma365.com/",
    c84:"https://kizen.com/",
    c85:"https://www.officeclip.com/",
    c86:"https://www.nocrm.io/",
    c87:"https://www.superoffice.com/",
    c88:"https://www.edgecrm.app/",
    c89:"https://www.teamleader.eu/",
    c90:"https://www.contactsplus.com/",
    c91:"https://www.salesboom.com/",
    c92:"https://help.sap.com/",
    c93:"https://www.greenrope.com/",
    c94:"https://www.honeybook.com/",
    c95:"https://www.allprowebtools.com/",
    c96:"https://zapier.com/",
    c97:"https://instream.io/",
    c98:"https://www.efficy.com/",
    c99:"https://www.act.com/",
    c100:"https://vipecloud.com/",




    c101:"https://www.ringy.com/",
    c102:"https://www.20nine.com/",
    c103:"https://opencrm.co.uk/",
    c104:"https://www.clientjoy.io/",
    c105:"https://rolldog.com/",
    c106:"https://kylas.io/",
    c107:"https://www.qontak.com/",
    c108:"https://www.vobesoft.com/",
    c109:"https://www.mothernode.com",
    c110:"https://teamwave.com/",
    c111:"https://www.agilecrm.com/",
    c112:"https://www.odoo.com/",
    c113:"https://www.funnelcrm.com/",
    c114:"https://addresstwo.com/",
    c115:"https://www.platformly.com/",
    c116:"https://www.maximizer.com/",
    c117:"https://www.planplusonline.com/",
    c118:"https://www.arkflux.com/",
    c119:"https://infoflosolutions.com/",
    c120:"https://www.outreachcrm.co.nz/",
    c121:"https://sellfapp.com/",
    c122:"https://www.propellercrm.com/",
    c123:"https://www.microsoft.com/",
    c124:"https://tapdesk.io/",
    c125:"https://covve.com/",
    c126:"https://www.knack.com/",
    c127:"https://www.oracle.com/",
    c128:"https://www.worketc.com/",
    c129:"https://www.espocrm.com/",
    c130:"https://crm.me/",
    c131:"https://www.relenta.com/",
    c132:"https://gleanview.com/",
    c133:"https://www.zoho.com/",
    c134:"https://www.sage.com/",
    c135:"https://www.vtiger.com/",
    c136:"https://www.clienttether.com/",
    c137:"https://www.salesnexus.com/",
    c138:"https://www.zoho.com/",
    c139:"https://www.pulsetechnology.com/",
    c140:"https://promys.org/",
    c141:"https://www.leadmaster.com/",
    c142:"https://suitecrm.com/",
    c143:"https://www.leadscore.io/",
    c144:"https://www.fivecrm.com/",
    c145:"https://www.oracle.com/",
    c146:"https://www.clientbook.com/",
    c147:"https://www.aurea.com/",
    c148:"http://www.xpo-online.com/",
    c149:"https://www.teamwork.com/",
    c150:"https://www.avidian.com/",




    c151:"https://www.signpostindia.com/",
    c152:"https://user.com/",
    c153:"https://www.salesbabu.com/",
    c154:"https://www.sales-i.com/",
    c155:"https://www.centrahubcrm.com/",
     c156:"https://www.womply.com/",
    c157:"http://www.clevertim.com/",
    c158:"https://www.gohighlevel.com/",
    c159:"https://www.intouchcrm.com/",
    c160:"https://www.amocrm.com/",
    c161:"https://www.forcemanager.com/",
    c162:"https://www.salesdesk.ae/",
    c163:"https://www.espocrm.com/",
    c164:"https://gridle.one/",
    c165:"https://www.oracle.com/",
    c166:"https://www.bigin.com/",
    c167:"https://contactease.blog/",
    c168:"https://www.marketing360.com/",
    c169:"https://www.infor.com/",
    c170:"https://digitalcrm.com/",
    c171:"https://www.salesjunction.com/",
    c172:"https://www.karmacrm.com/",
    c173:"https://soffront.com/",
    c174:"https://www.orangecrm.com/",
    c175:"https://www.aptean.com/",
    c176:"https://www.simpleviewinc.com/",
    c177:"https://www.revampcrm.com/",
    c178:"https://oroinc.com/",
    c179:"https://est05.esalestrack.com/",
    c180:"https://yetiforce.com/",
    c181:"https://1crm.com/",
    c182:"https://www2.netx360.com/",
    c183:"https://freecrm.com/",
    c184:"https://crmconnect.be/",
    c185:"https://solve360.com/",
    c186:"https://www.goldmine.co.in/",
    c187:"https://www.talisma.com/",
    c188:"https://en.wemine.hk/",
    c189:"https://tilda.cc/",
    c190:"https://www.cuspera.com/",
    c191:"https://www.vtiger.com/",
    c192:"https://en.wikipedia.org/",
    c193:"https://commence.com/",
    c194:"https://tigerpaw.com/",
    c195:"https://www.launchpadmediamanagement.com/",
    c196:"https://www.inmindcloud.com/",
    c197:"https://www.onlyoffice.com/",
    c198:"https://overloop.com/",
    c199:"https://go.sellsy.com/",
    c200:"https://upilot.com/",
    c201:"https://visionflow.com/",
    c202:"https://centralstationcrm.com/",
    c203:"http://ww17.core3crm.com/",
    c204:"https://mazrica.com/",
    c205:"https://sleekflow.io/",
    c206:"https://www.sunsmart.co.in/",
    c207:"https://www.sunsmart.co.in/",




    c208:"https://cross-crm.com/",
    c209:"https://www.equisoft.com/",
    c210:"https://www.metrilo.com/",
    c211:"https://www.aacesoft.com/",
    c212:"https://augutechcorp.com/",
    c213:"https://bizpluscrm.com/",
    c214:"https://www.bluwave.co.za/",
    c215:"http://www.fatfreecrm.com/",
    c216:"https://fluentcrm.com/",
    c217:"https://www.leadloft.com/",
    c218:"http://www.mdcdot.com/",
    c219:"http://www.mdcdot.com/",
    c220:"https://www.sydle.com/",
    c221:"https://www.thecrm.com/",
    c222:"https://verenia.com/",
    c223:"https://zigihub.com/",
    c224:"https://www.bsi-software.com/",
    c225:"https://www.bsi-software.com/",
    c226:"https://jungleworks.com/",
    c227:"https://crm.io/",
    c228:"https://www.dejaoffice.com/",
    c229:"https://evergenius.com/",
    c230:"https://www.franconnect.com/",
    c231:"https://www.conarc.com/",
    c232:"https://www.keyoffice.org/",
    c233:"https://www.kreatocrm.com/",
     c234:"https://www.kreatocrm.com/",
   
    c235:"https://www.m2wealth.com/",
    c236:"https://www.maghub.com/",
    c237:"https://www.opencrx.org/",
    c238:"https://ricochet360.com/",
    c239:"https://www.teamgate.com/",
    c240:"https://trueclientpro.com/",
    c241:"https://www.wp-crm.com/",
    c242:"https://www.absolutebusy.com/",
    c243:"https://www.acuitycrm.co.za/",
    c244:"https://appshore.com/",
    c245:"https://aquacrm.mx/",
    c246:"https://www.auricprospector.com/",
    c247:"https://bizscheduler.com/",
    c248:"https://www.bxpsoftware.com/",
    c249:"http://centriumcrm.com/",
    c250:"https://channelonline.com/",

//from 1to 250 not miss


    c251:"https://www.cloze.com/",
    c252:"https://www.contactwise.io/",
    c253:"https://cratiocrm.com/",
    
   c254:"https://www.salesbabu.com/",
    c255:"https://www.darzin.com/",
    c256:"https://deltatechnepal.com/",
    c257:"https://www.deskera.com/",
    c258:"https://www.eway-crm.com/",
    c259:"https://www.fortifi.com/",
    c260:"https://www.frmsolutions.com/",
    c261:"https://gbs.com/",
    c262:"https://www.genesys.com/",
    c263:"http://h2oworks.co/",
    c264:"https://www.honchocrm.com/",
    c265:"https://www.imprezian360.com/",
    c266:"https://www.inboundio.com/",
    c267:"https://ivinex.com/",
    c268:"https://ivinex.com/",
    
    c269:"http://www.keiwareapplications.com/",
    c270:"https://www.livespace.io/",
    c271:"https://www.luitinfotech.com/",
    c272:"https://www.maplecrm.com",
    c273:"http://mediarails.com/",
    c274:"https://www.minicrm.io/",
    c275:"https://www.minicrm.io/",
 
    c276:"https://www.openstream.ai/",
    c277:"https://www.outfieldapp.com/",
    c278:"https://www.pega.com/",
    c279:"https://prorm.net/",
    c280:"https://dalcotech.com/",
    c281:"https://dalcotech.com/",
    
    c282:"https://www.ringbyname.com/",
    c283:"https://www.salesoptima.com/",
    c284:"https://www.salestrakr.com/",
    c285:"https://www.simplecrm.com/",
    c286:"https://www.smartsearch.com/",
    c287:"https://www.surefyre.co/",
    c288:"https://t3softwares.com/",
    c289:"https://www.univention.com/",
    c290:"https://getfishtank.ca/",
    c291:"http://tvarak.com/",
    c292:"https://www.w3bcrm.biz/",
    c293:"https://wice.de/",
    c294:"https://www.zyprr.com/",
    c295:"https://www.crunchbase.com/",
    c296:"https://360enterprisesuite.com/",
    c297:"https://www.8amweb.com/",
    c298:"https://www.90degreeteamtask.com/",
    c299:"https://lineup.com/",
}



/*








    c300:"https://www.advanceinnovationgroup.com/",
    c301:"https://www.getadvantage.com/",
    c302:"https://www.affino.com/",
    c303:"https://www.agencyorganizer.com/",
    c304:"https://crm.alore.io/",
    c305:"http://www.apiscrm.com/",
    c306:"http://ardexus.com/",
    c307:"https://www.aurocrm.com/",
    c308:"https://www.aurocrm.com/",
    c309:"https://www.bioscrm.com/",
    c310:"https://www.bizstim.com/",
    c311:"https://boxxstep.com/",
    c312:"https://bridg.com/",
    c313:"https://apps.apple.com/",
    c314:"https://callprocrm.com/",
    c315:"https://www.cas-crm.com/",
    c316:"https://www.cliengo.com/",
    c317:"https://www.cloudcc.cn/",
    c318:"https://www.combit.com/",
    c319:"https://composity.com/",
    c320:"https://www.g2.com/",

}



/*

    c:"https://coretal.co/
    c:"https://cotano.me/
    c:"https://counterbalance.org/
    c:"https://www.cruzatasoft.com/",portfolio/cruzata-CRM
    c:"https://www.crunchbase.com/",organization/cuesent
    http://www.callippus.co.uk/
    c:"https://gsd-software.com/",
    
    c:"https://www.eccentex.com/",
    c:"https://elitecampaign.com/",
    c:"https://www.emailgreen.com/",
    c:"https://epesi.org/
    c:"https://www.exerterp.com/",customer-relationship-management
    c:"https://getflg.com/",
    http://ftcrm.fiamma.com.",my/fiamma/login.asp
    c:"https://www.gold-vision.com/",
    c:"https://inforgen.com/",
    c:"https://inperium.com/",sales-crm-system
    c:"https://www.binarytechnologies.co.uk/
    c:"https://intellistant.com/",
    http://www.intrabench.com/",
    c:"https://btssoft.net/
    http://www.leadprime.com/",
    c:"https://www.leadtrack.com/",
    c:"https://www.magiccrm.it/it/
    c:"https://www.marsdd.com/",
    NA
    c:"https://www.metroleads.com/",
    c:"https://www.mimiran.com/",
    c:"https://www.phpcrm.com/",
    NA 
    c:"https://www.power-crm.net/
    c:"https://www.qebot.com/",crm/
    c:"https://www.nchsoftware.com/",
    c:"https://www.salesnow.com/",
    c:"https://www.salesprocrm.com/",
    c:"https://www.salesseek.com/",
    c:"https://salesup.com/",
    c:"https://saleswah.com/",
    http://www.sentia.in/
    c:"https://smartfunnel.com/",
    c:"https://www.spmarketplace.com/",office-365-sharepoint-crm.html
    c:"https://www.spinso.com/",eqms/screens/index.htm
    c:"https://mailchimp.com/",integrations/sugarchimp-sugarcrm-integration/
    c:"https://www.rediansoftware.com/",
    c:"https://swiftcrm.com/",#solveTraffic
    c:"https://www.thebusiness360.com/",
    c:"https://www.toolyt.com/",
    c:"https://www.veloxity.com/",
    c:"https://vivoinitio.com/",
    c:"https://webcrm.com/",uk/
    c:"https://www.wesuite.com/",
    c:"https://www.workxmate.com/",
    c:"https://www.wyverndm.co.uk/CRM-Software/WyvernMagic
    http://www.zavanti.com/",crm/
    c:"https://www.123coimbatore.com/",customized-crm-software-in-coimbatore/
    c:"https://www.theaccessgroup.com/",
    c:"https://www.adsystems-sa.com/",
    c:"https://anthill.co.uk/
    
    c:"https://salesways.com/",
    c:"https://www.atemiscloud.com/",
    c:"https://atendare.com/",
    c:"https://apps.avisi.com/",apps/atlas-crm-overview
    c:"https://www.atollon.com/",
    c:"https://axonaut.com/",en
    c:"https://www.axsar.com/",axsar-solo/
    c:"https://ayudasystems.pr.co/
    c:"https://basix.ai/
    c:"https://bixpand.com/",
    c:"https://www.obn.uk.com/",products_and_services/business_software/black_ice_crm
    c:"https://www.bluecamroo.com/",
    c:"https://www.bpa-solutions.net/
    c:"https://www.britebiz.com/",
    c:"https://buddycrm.com/",
    c:"https://www.cas-crm.com/",
    http://cerrebro.com/",
    c:"https://clinchpad.com/",
    c:"https://www.cloudnet360.com/",
    c:"https://www.brightoffice.co.uk/
    c:"https://conduithq.com/",
    c:"https://www.conrep.com/",modules/customer-management-crm/
    c:"https://www.contactbox.pro/
    c:"https://coollife.io/
    c:"https://www.hugedomains.com/",
    NA
    c:"https://www.crmboost.com/",
    c:"https://www.crm.es/
    c:"https://www.unleashedsoftware.com/",
    c:"https://www.datacor.com/",products/datacor-crm
    c:"https://www.deepser.com/",
    http://www.thecrmguide.com/",
    c:"https://www.divyacloud.com/",
    c:"https://www.dolicloud.com/",
    c:"https://www.dquip.com/",
    c:"https://ecosagile.com/",ENG/software-crm-cloud
    c:"https://eduagentcrm.com/",
    c:"https://ensourcepay.com/",#/login
    c:"https://esolarcrm.com/",
    c:"https://www.ewhizsales.com/",
    c:"https://www.eznetcrm.com/",
    c:"https://fiitfu.com/",
    c:"https://flashcx.ai/
    c:"https://flexie.io/
    c:"https://flightdeckcrm.co.uk/
    http://www.fmr-systems.com/",
    c:"https://www.fundstack.ltd/
    c:"https://funnelflare.io/
    c:"https://www.funnelmaker.com/",
    c:"https://www.gayatrisoft.co/
    NA
    c:"https://gincore.net/en
    c:"https://www.grocrm.com/",
    c:"https://happsales.com/",
    c:"https://www.haystackcrm.com/",
    c:"https://www.hogunsoft.com/",
    c:"https://www.hyperteam.com/",hyperteam-crm
    c:"https://whitefluffy.cloud/
    c:"https://ienterprises.com/",
    c:"https://www.iglobecrm.com/",
    c:"https://www.inboldsolutions.com/",
    c:"https://www.inditioncrm.com/",
    c:"https://www.efficy.com/",efficy-vs-ines-crm/
    c:"https://app.infinitecrm.io/login
    c:"https://www.infocdb.com/",
    c:"https://www.infositetech.com/",crm.php
    c:"https://iqdesk.com/",
    c:"https://www.istrives.com/",
    http://www.itisl.com/",
    c:"https://jigawatt.solar/
    c:"https://kordeva.com/",
    c:"https://kulahub.com/",
    c:"https://www.legrandcrm.com/",
    c:"https://www.liono360.com/",
    c:"https://www.logicbox.co/
    c:"https://www.loyaltyplus.cloud/
    c:"https://www.lunasoft.com/",crm-contact-management.php
    c:"https://macantacrm.com/",
    c:"https://www.managemore.com/",
    c:"https://mantle-crm.medium.com/",
    c:"https://www.markate.com/",
    c:"https://www.maxcustomer.com/",
    c:"https://www.mcasuite.com/",
    c:"https://www.meracrm.com/",
    NA
    c:"https://www.moskitcrm.com/",
    c:"https://www.mybusiness-websuite.com/",
    c:"https://www.mycosuite.com/",en/home
    c:"https://www.groupfio.com/",
    http://neocrm.in/
    c:"https://ninjodo.com/",
    http://www.notchitup.com/",
    c:"https://www.octopuspro.com/",
    c:"https://www.ofisim.com/",
    c:"https://www.onesheetcrm.com/",
    c:"https://www.onsitecrm.com/",
    c:"https://www.opera.com/",
    c:"https://www.optifinow.com/",
    c:"https://orion-soft.com/",en/products/erp/
    c:"https://www.osmoscloud.com/",en/home
    c:"https://o360.com/",
    c:"https://www.phingoocrm.com/",
    c:"https://crmpiperun.com/",
    c:"https://www.planmill.com/",
    c:"https://www.pmamcrm.com/",
    c:"https://secure.proabd.com/",
    c:"https://prosperna.com/",
    c:"https://thepulsespot.com/",
    c:"https://pype.co/
    c:"https://qraia.com/",en/home-2/
    c:"https://www.quickdesk.io/
    NA
    NA
    c:"https://rainbowriders.dk/case/rainbow-crm/
    http://www.rangermsp.com/",
    c:"https://ready-os.com/",pl/
    c:"https://redhorsesystems.com/",
    c:"https://www.roboeyelabs.com/",
    c:"https://runo.in/
    NA
    c:"https://www.creatio.com/",sales
    NA
    c:"https://www.salesinfinite.com/",
    http://www.salesinsync.com/",
    c:"https://www.hugedomains.com/",
    http://www.salesmantra.com/",
    c:"https://www.salesoutlook.com/",
    c:"https://salessimplify.com/",
    c:"https://www.salestango.com/",
    c:"https://saleswon.com/",
    c:"https://sanityos.com/",
    c:"https://www.aurea.com/",
    c:"https://a.captchaless.top/robot4/?c=1f0ef619-502c-4ff1-83f5-745c7491f1f8&a=l15369#
    c:"https://www.secondcrm.com/",
    c:"https://sendpulse.com/",
    c:"https://shark-byte.com/",
    c:"https://shootq.com/",
    c:"https://www.simplicitycrm.com/",products/enterprise-crm.aspx
    c:"https://www.skywardcrm.com/",
    c:"https://smalution.com/",
    c:"https://www.smartcomp",any.net/
    c:"https://www.snapforce.com/",
    c:"https://www.sobiacanyon.com/",
    c:"https://www.soulcrm.com/",
    c:"https://www.spicecsm.com/",products/engagement-suite
    c:"https://www.spincrm.com/",en/
    c:"https://startercrm.com/",
    c:"https://sugester.com/",
    c:"https://suitecrm.com/",enterprise/suiteassured/
    c:"https://suitecrm.com/",
    c:"https://www.sunbearsoftware.net/
    c:"https://www.sutisoft.com/",crm-software/
    NA
    c:"https://www.symvolli.com/",
    c:"https://taskeo.co/
    c:"https://www.teamgram.com/",main/en/
    c:"https://teknovativesolution.com/",
    c:"https://telenotes.com/",
    c:"https://pos.toasttab.com/",solutions/guest-facing-technology
    http://www.triumphcrm.com/",
    c:"https://www.tugbiz.com/",
    c:"https://tracxn.com/",d/comp",anies/ubicrm.com
    ",c:"https://www.valuecreationautomation.com/",
    c:"https://www.velacrm.com/",
    NA
    c:"https://www.venntive.com/",
    c:"https://vinconnect.com/",
    c:"https://www.vitalblocks.com/",
    c:"https://www.wakeupsales.com/",
    c:"https://www.ibm.com/",in-en
    c:"https://www.wintouch.com/",
    c:"https://wiredcontact.com/",
    c:"https://wooster.edu/
    http://www.72crm.org/
    http://www.zimplu.com/",
    c:"https://zoomaworks.com/",
    c:"https://www.800app.com/",
    c:"https://adsalesgenius.com/",
    c:"https://ignitetech.com/",softwarelibrary/agemni
    c:"https://ambine.com/",
    c:"https://amiga.com/",
    c:"https://anbiz.com/",
    c:"https://www.aptania.com/",
    http://crm.e-arc.com/",login.asp
    c:"https://archizsolutions.com/",
    c:"https://aritic.com/",
    c:"https://www.assetdatamanager.com/",
    c:"https://attio.com/",
    c:"https://www.aurea.com/",
    c:"https://www.aurocrm.com/",
    http://www.authentic-ventures.com/",
    c:"https://axelor.com/",
    c:"https://barantum.com/",
    c:"https://bascrm.com/",
    c:"https://www.basiconline.net/saas-cloud-crm-x.html
    c:"https://www.netkarma.ca/
    c:"https://beanstalkwebsolutions.com/",blog/crm-software-solutions/
    c:"https://www.beetle-eye.com/",
    c:"https://bluetrait.com/",
    c:"https://www.captecsystems.com/",crm
    c:"https://www.cas-pia.com/",
    c:"https://clatos.com/",
    c:"https://clockworkcrm.com/",
    c:"https://www.targetfirst.com/",
    NA
    c:"https://www.conductcrm.com/",
    c:"https://cm.consol.com/",
    http://www.contactfile.co.uk/
    NA
    c:"https://www.cordis.us/saudi-arabia/customer-relationship-management-system/
    c:"https://crankcrm.com/",
    c:"https://www.crmsoda.com/",
    c:"https://crestsolution.com/",
    c:"https://crm.org/crmland/what-is-a-crm
    c:"https://www.zendesk.com/",in/marketplace/apps/support/227130/crm-for-zendesk/
    c:"https://contactboss.com/",
    c:"https://crmservice.com/",
    c:"https://www.crump.tech/crump/
    c:"https://www.planetcrust.com/",
    c:"https://www.infor.com/",
    c:"https://crm.org/crmland/what-is-a-crm
    c:"https://getfly.vn/
    c:"https://www.daffodilsw.com/",custom-crm-development-services
    c:"https://www.dendreo.com/",
    c:"https://www.alepo.com/",
    c:"https://www.dinamikcrm.com/",
    c:"https://django-crm.readthedocs.io/en/latest/
    c:"https://dream-base.com/",
    c:"https://www.easynow.app/
    NA
    c:"https://edifybiz.com/",
    c:"https://www.edvertica.com/",
    NA
    c:"https://www.etiya.com/",en/products/customer-relationship-management
    c:"https://ezeesolution.com/",crm.php
    c:"https://www.fincrm.net/
    c:"https://firmao.net/
    c:"https://www.flashlead.com/",
    c:"https://flavorcrm.com/",
    c:"https://www.folk.app/
    c:"https://www.franchiczar.com/",software/
    c:"https://www.freshworks.com/",
    c:"https://fridaycrm.com/",
    c:"https://www.fruitionpartners.nl/
    c:"https://getfly.vn/
    c:"https://www.glazecrm.com/",
    c:"https://globagilityinc.com/",
    c:"https://greatsoft.co.za/
    c:"https://greyhound-software.c
    c:"https://www.groundhogg.io/
    c:"https://growcrm.io/
    c:"https://www.hotprospectscrm.com/",
    c:"https://ictcrm.com/",
    c:"https://www.idocpro.de/impressum/
    c:"https://www.imaginesales.co/call-center-apps/amp/
    http://improo.me/
    c:"https://indydesk.com/",
    c:"https://www.insight.com/",en_US/what-we-do/digital-innovation/services/crm-services.html
    c:"https://instacap.in/
    c:"https://www.intellicrm.com/",
    c:"https://www.intellidialer.com/",
    c:"https://www.intrixcrm.com/",en/
    c:"https://ioss.in/crm-software/
    c:"https://itracmarketer.com/",
    c:"https://mdpgroup.com/",en/
    NA
    NA
    c:"https://leadsales.io/en/home/
    c:"https://leadsnap.com/",
    c:"https://leadzy.io/
    c:"https://lemontechnologies.net/
    c:"https://www.loyaltyleader.com/",
    c:"https://www.massistcrm.com/",
    c:"https://www.membes.com.",au/
    c:"https://www.fusionsoftware.co.za/crm
    c:"https://www.milocrm.com/",
    c:"https://mindqube.com/",
    c:"https://www.mobiantsolutions.com/",
    c:"https://mokapen.com/",en
    c:"https://www.monosolutions.com/",
    c:"https://moovago.com/",en/home/
    c:"https://motilitysoftware.com/",
    c:"https://moverstech.com/",
    c:"https://mybirdy.co.uk/
    c:"https://mycrms.com/",
    http://myworkspace.com/",
    c:"https://nafhaa.com/",
    c:"https://nat.app/
    c:"https://www.navigaglobal.com/",
    http://www.ngage.com/",
    c:"https://www.tryoncourse.com/",
    c:"https://www.onebillsoftware.com/",customer-relationship-management/
    c:"https://onedigiflow.com/",
    c:"https://www.onelocal.com/",
    c:"https://www.onpipeline.com/",
    c:"https://www.opalcrm.com/",
    http://www.oprius.com/",
    c:"https://www.optimiser.com/",
    c:"https://pegasuscrm.net/
    c:"https://peppercloud.com/",
    c:"https://www.preliotech.com/",
    c:"https://www.privyr.com/",?utm_source=google&utm_medium=cpc&utm_campaign=13798873130&utm_content=125390132078&utm_term=%2Bprivyr&gclid=CjwKCAjw_ISWBhBkEiwAdqxb9i6KRAPCtXLPkdveAIR-AzRHOfNWYYDTgEU6d190HLJcGC6kviUXIxoCWIcQAvD_BwE
    c:"https://prospur.io/error
    c:"https://www.gripp.com/",
    NA
    c:"https://qymatix.de/en/
    c:"https://www.rapidstartcrm.com/",
    c:"https://results-software.com/",get-started/sg/
    c:"https://www.revolsolutions.com/",
    NA
    c:"https://rizer.in/
    c:"https://www.rubicrm.com/",
    c:"https://www.s4ds.com/",
    c:"https://salemaxplus.com/",
    c:"https://www.salescamp.app/
    c:"https://www.salescandy.com/",
    c:"https://salesdashcrm.com/",
    http://www.rti-software.com/",
    c:"https://salesflow.io/
    c:"https://salesfokuz.com/",
    c:"https://saysimple.com/",
    c:"https://www.secondcrm.com/",
    c:"https://www.sellsation.com/",
    http://selltis.com/",
    c:"https://seocrm.com/",
    c:"https://www.seotoaster.com/",crm/
    c:"https://www.servitiumcrm.com/",
    c:"https://sherpacrm.com/",
    c:"https://shinebox.com/",
    c:"https://www.cloudapper.com/",
    c:"https://www.simplecrm.com/",
    c:"https://www.simplemobilecrm.com/",
    c:"https://simplesalestracking.com/",
    c:"https://www.skale.today/
    c:"https://skywave.app/
    c:"https://www.smarttouchinteractive.com/",technology/nexgen-crm/
    c:"https://www.starcrm.com.",my/
    http://www.stellarite.com/",
    c:"https://www.stingosales.com/",
    c:"https://strategicerp.com/",b2b-crm-software.php
    c:"https://store.outrightcrm.com/",product/suitecrm-faster-global-search-premium/
    c:"https://store.suitecrm.com/",addons/dropdown-values-import
    c:"https://store.suitecrm.com/",addons/user-activity-tracker/comp",atibility
    c:"https://tallemucrm.com/",
    c:"https://team365.io/
    c:"https://www.teamsystem.com/",teamsystem-enterprise-crm
    c:"https://technomile.com/",products/growth-suite/
    c:"https://smartmatchapp.com/",
    c:"https://falconvsystems.com/",
    c:"https://www.tigerlrm.com/",
    c:"https://help.tikit.ai/
    c:"https://www.toolsoncloud.com/",
    c:"https://www.toppr.com/",
    c:"https://www.totalcontrolpro.com/",
    c:"https://trackpm.com.",au/
    c:"https://www.turnkeylinux.org/
    c:"https://www.twilead.com/",
    c:"https://www.twilio.com/",docs
    http://www.twistoe.com/",landing
    c:"https://unifyy.com/",
    c:"https://upnify.com/",
    c:"https://www.utiliko.io/business-management-app/
    c:"https://velosiaims.com/",service/softwareservices/vailcrm/
    c:"https://torncrm.com/",crm/valueframe-psa-pro/
    c:"https://variablesoft.com/",crm
    c:"https://infinisystem.com/",veefin-customer-relationship-management/
    c:"https://www.voiie.com/",
    c:"https://www.vryno.com/",
    c:"https://www.vtenext.com/",en/
    c:"https://www.vyoog.com/",
    c:"https://www.wavity.com/",crm/
    c:"https://en.webmecanik.com/",
    c:"https://whitecupsolutions.com/",
    c:"https://www.whiztec.com/",srm.php
    http://wisdomcrm.ai/
    c:"https://worldphone.in/
    http://www.xcrm.com/",
    c:"https://xlr8sport.in/
    c:"https://torncrm.com/",crm/xoomsales/
    c:"https://www.yathit.com/",
    c:"https://www.zeyos.com/",
    c:"https://spiff.com/",
    c:"https://www.captivateiq.com/",
    c:"https://www.varicent.com/",
    c:"https://www.xactlycorp.com/",products/incentive-comp",ensation-management-software
    c:"https://www.everstage.com/",
    c:"https://www.xoxoday.com/",
    c:"https://www.quotapath.com/",
    c:"https://www.performio.co/
    c:"https://paletteskills.org/programs/salescamp
    c:"https://www.forma.ai/
    c:"https://elevate.so/
    c:"https://www.sap.com/",india/products/comm",issions.html
    c:"https://www.oracle.com/",in/cx/sales/sales-performance-management/
    c:"https://kennect.io/
    c:"https://salescookie.com/",
    c:"https://www.smartwinnr.com/",
    c:"https://iconixx.com/",
    c:"https://www.qcomm",ission.com/",
    c:"https://xactly.simplycomp",.com/",login
    c:"https://www.vistex.com/",solutions-sap/
    c:"https://www.easy-comm",ission.com/",
    c:"https://www.comm",issionly.io/
    c:"https://www.xactlycorp.com/",products/comm",ission-expense-accounting
    c:"https://www.qobra.co/
    c:"https://optymyze.com/",
    c:"https://iconixx.com/",solutions/incentive-comp",ensation-management
    c:"https://corecomm",issions.com/",
    c:"https://www.zs.com/",products/jav
    c:"https://www.amalia.io/
    c:"https://www.equalto.com/",
    c:"https://www.visualbonus.com/",
    c:"https://acsgbl.com/",products/access-comm",issions/
    c:"https://blog.cloudcomp",app.com/",
    c:"https://www.netcomm",issions.com/",
    c:"https://visdum.com/",
    c:"https://ancorasoftware.com/",
    c:"https://www.aurochssolutions.com/",incentive-calculation-manager/
    c:"https://www.axtria.com/",cloud-products/axtria-salesiq-sales-management-sales-planning-and-operations/
    c:"https://www.blitzrocks.com/",
    c:"https://www.broadridge.com/",financial-services/wealth-management/wealth/advance-control-risk-and-support-services/advisor-comp",ensation
    http://www.comm",issioncalc.com/",
    c:"https://www.simplenexus.com/",
    c:"https://glocent.com/",
    c:"https://idynamics-comm",issions.com/",
    c:"https://incentivate.in/
    c:"https://incentx.com/",
    c:"https://www.inlogic.in/
    c:"https://www.istrives.com/",
    c:"https://incentives-solutions.com/",
    c:"https://www.leaptree.com/",products/incentivize
    c:"https://mahalo-comm",issions.com/",
    NA
    c:"https://www.itagroup.com/",
    NA
    c:"https://sparkplug.app/
    c:"https://thinksmartone.com/",en/
    c:"https://www.vistex.com/",cloud-solutions/
    c:"https://www.hubspot.com/",products/sales
    c:"https://www.zoominfo.com/",
    c:"https://www.clari.com/",
    c:"https://scratchpad.com/",
    c:"https://www.dooly.ai/
    c:"https://people.ai/
    c:"https://www.trywingman.com/",
    c:"https://www.troops.ai/
    c:"https://www.drift.com/",
    c:"https://www.conversica.com/",
    c:"https://www.writecream.com/",
    c:"https://www.zoho.com/",zia/
    c:"https://www.insidesales.com/",
    c:"https://www.dialpad.com/",sell/
    c:"https://www.aviso.com/",
    c:"https://amplemarket.com/",
    c:"https://www.kixie.com/",features/kixie-powercall/
    c:"https://veloxy.io/
    c:"https://www.introhive.com/",
    c:"https://verse.io/
    c:"https://www.dnb.com/",products/marketing-sales/dnb-hoovers.html
    c:"https://revenuegrid.com/",
    c:"https://www.kronologic.ai/
    c:"https://www.copilotai.com/",
    c:"https://www.insightsquared.com/",
    c:"https://exceed.ai/conversation-marketing-and-sales-platform-1/
    c:"https://www.linkedhelper.com/",
    c:"https://www.pickleai.com/",
    c:"https://www.fullcircl.com/",
    c:"https://humantic.ai/
    c:"https://saile.ai/
    c:"https://www.salesdirector.ai/
    c:"https://www.saleswhale.com/",
    c:"https://zopto.com/",
    c:"https://www.zoho.com/",zia/
    c:"https://www.tact.ai/
    c:"https://www.rollio.ai/
    c:"https://www.zilliant.com/",
    c:"https://www.augmentcxm.com/",
    c:"https://goodmeetings.ai/
    c:"https://www.xactlycorp.com/",products/intelligent-sales-forecasting
    c:"https://zoovu.com/",
    c:"https://www.mightyforms.com/",
    c:"https://spotler.co.uk/
    c:"https://sendzilla.io/
    c:"https://www.cloze.com/",
    c:"https://chatfunnels.com/",
    c:"https://www.prodoscore.com/",
    c:"https://www.airudder.com/",
    c:"https://www.setsail.co/
    c:"https://woobot.io/
    c:"https://proton.me/
    c:"https://www.upscale.cash/?utm_source=Google_Ads&utm_medium=Search&utm_campaign=Unknown&utm_id=UpScale_TP_28thFeb22_Unknown&utm_term=Branded_Unknown&utm_content=English_Branded_RSA&gclid=Cj0KCQjwn4qWBhCvARIsAFNAMihVFk77Hhf1bRrcef-rni2rs17XUxjY2J1vow38alOgFZgQ6hSu2UgaAk4CEALw_wcB
    c:"https://draup.com/",sales/
    c:"https://www.salesforce.com/",ap/products/platform/features/
    c:"https://accent-technologies.com/",
    c:"https://engageiq.com/",
    c:"https://www.growthleads.com/",
    c:"https://hummingbirds.ai/
    c:"https://linkedcamp.com/",
    c:"https://orm-tech.com/",
    c:"https://salesflare.com/",index.html
    c:"https://www.koncert.com/",
    c:"https://www.pega.com/",
    c:"https://www.regie.ai/
    c:"https://collectivei.com/",
    c:"https://www.getciara.com/",
    c:"https://www.cloudapps.com/",
    c:"https://www.lead411.com/",
    c:"https://www.writelola.ai/
    c:"https://themanagr.in/home
    c:"https://neobiz.app/#
    c:"https://getpenny.com/",
    c:"https://salesbox.ai/
    c:"https://www.structurely.com/",
    http://www.ubico.in/
    c:"https://www.verticalls.ai/
    c:"https://woodpecker.co/
    c:"https://7targets.ai/
    c:"https://www.aider.ai/
    c:"https://crm.alore.io/#/
    c:"https://myamy.io/
    NA
    c:"https://www.ciena.com/",
    c:"https://clay.global/
    c:"https://clodura.ai/
    c:"https://crmx.cloud/
    c:"https://crono.app/
    c:"https://delpha.io/
    c:"https://digitalairstrike.com/",
    c:"https://www.edward.ai/en/home
    c:"https://www.egain.com/",
    c:"https://ellie.ai/
    c:"https://everready.ai/e
    c:"https://www.followupthen.com/",
    c:"https://gryphon.ai/
    c:"https://hq.hatcher.com/",
    c:"https://humach.com/",digital-agents/
    c:"https://www.humanic.net/at
    http://hypadrive.ai/
    c:"https://inforobo.com/",
    c:"https://hubkn.com/",
    c:"https://www.kindly.ai/
    c:"https://www.lavender.ai/
    c:"https://magefan.com/",
    c:"https://www.mav.it/en/
    c:"https://www.absolutdata.com/",
    c:"https://nektar.ai/
    c:"https://neohelden.com/",de/
    c:"https://notesally.com/",
    c:"https://oliverlist.com/",
    c:"https://www.outreachy.org/
    c:"https://perfectprospect.io/
    c:"https://www.persistence.ai/
    c:"https://pickyassist.com/",en/
    c:"https://pobuca.com/",
    c:"https://contractpodai.com/",
    c:"https://www.resonance.ac.in/
    http://www.markitsoft.com/",
    c:"https://salesrobots.pl/pl
    c:"https://scalex.ai/
    c:"https://www.verticalls.ai/
    NA
    c:"https://www.strise.ai/
    c:"https://techsalesbox.com/",
    c:"https://thumb-crowd.com/",
    c:"https://www.unique.ai/
    c:"https://www.virasoft.com/",decision-support-ai
    c:"https://vizerto.com/",
    c:"https://www.winware.ai/
    c:"https://www.talkdesk.com/",
    c:"https://www.nice.com/",products
    c:"https://www.genesys.com/",genesys-cloud
    c:"https://www.five9.com/",
    c:"https://www.phoneburner.com/",
    c:"https://www.cloudtalk.io/
    c:"https://aloware.com/",
    c:"https://www.zoominfo.com/",products/engage
    c:"https://www.dialpad.com/",sell/
    c:"https://justcall.io/?fp_ref=matt68
    c:"https://www.kixie.com/",features/kixie-powercall/
    c:"https://livevox.com/",
    c:"https://www.orum.com/",
    c:"https://calltools.com/",
    c:"https://setshape.com/",
    http://ca.ozonetel.com/",
    c:"https://vcc.live/
    c:"https://www.convoso.com/",
    c:"https://readymode.com/",
    c:"https://www.ringcentral.com/",contact-center/overview.html
    c:"https://www.onsolve.com/",platform-products/critical-comm",unications/one-call-now/
    c:"https://www.callfire.com/",
    c:"https://www.adversus.io/
    c:"https://www.acqueon.com/",
    c:"https://www.chasedatacorp.com/",
    c:"https://www.frontspin.com/",
    c:"https://voiptimecloud.com/",
    c:"https://www.mojosells.com/",
    c:"https://www.vonage.com/",contact-centers/
    c:"https://lm.velocify.com/",Web/Login.aspx
    c:"https://www.airudder.com/",
    c:"https://www.clickpointsoftware.com/",
    c:"https://fastcall.com/",
    c:"https://nobelbiz.com/",
    c:"https://www.ring.io/
    c:"https://sharpencx.com/",
    c:"https://www.alvaria.com/",
    c:"https://www.genesys.com/",en-sg
    c:"https://www.3clogic.com/",
    c:"https://www.getcalley.com/",
    c:"https://ricochet360.com/",
    c:"https://www.coms",yscx.com/",aspect-unified-ip/
    c:"https://leaddesk.com/",
    c:"https://www.spitfiredialers.com/",
    c:"https://www.2xconnect.com/",
    c:"https://www.comm",peak.com/",
    c:"https://www.dcdial.com/",
    c:"https://funnelflare.io/
    c:"https://www.goto.com/",ucaas/contact-center
    c:"https://www.intrado.com/",cloud-collaboration/contact-center/cloud-contact-pro#
    c:"https://leadsrain.com/",
    c:"https://www.outreach.io/
    c:"https://prospectboss.com/",
    c:"https://squaretalk.com/",
    http://www.tctecno.com/",
    c:"https://callbacktracker.com/",
    c:"https://www.contactspace.com/",
    c:"https://www.evs7.com/",
    c:"https://www.hellohunter.com/",
    c:"https://www.salessling.com/",
    c:"https://talkchief.io/en/
    c:"https://telemo.io/
    c:"https://tp-smart.en.uptodown.com/",android/download
    c:"https://www.3cx.com/",docs/cfd-creating-outbound-dialer/
    c:"https://vagent.in/
    c:"https://www.amplifai.com/",
    c:"https://www.acarda.com/",
    c:"https://www.astargroup.org/auto-dialer-app/
    c:"https://www.dynamicic.com/",
    c:"https://www.tti.net/
    c:"https://brax.tel/
    c:"https://3gcallnet.com/",
    c:"https://www.callcenterhosting.com/",
    c:"https://www.calllogic.com/",
    c:"https://callonthego.com/",autodialers
    c:"https://www.callshaper.com/",
    c:"https://clientcallplus.com/",
    NA 
    c:"https://www.evolveip.net/?hsLang=en
    c:"https://www.hostcomm",.co.uk/
    c:"https://dialer.ai/
    http://ww25.dialermax.com/",?subid1=20220705-1908-28bd-93a8-7fcc85ca83af
    c:"https://buzzworks.com/",
    c:"https://www.dialerspro.com/",
    http://dynamicstelephony.com/",
    c:"https://edify.cx/
    c:"https://enghouseinteractive.com/",SmartDial
    c:"https://focustelecom.",eu/call-center-software/
    c:"https://voipinvite.com/",
    c:"https://www.hosteddialer.in/
    c:"https://ictbroadcast.com/",
    c:"https://www.knowlarity.com/",voice/number-masking
    c:"https://www.leapcaller.com/",
    c:"https://www.lucrativ.com/",
    c:"https://www.maxcontact.com/",
    c:"https://megacall.es/en/
    c:"https://osdial.com/",
    c:"https://phonetag.co/
    c:"https://www.pimsware.com/",
    c:"https://kavkom.com/",
    c:"https://www.dialerindia.com/",
    c:"https://www.dynamicic.com/",
    c:"https://primodialler.com/",
    c:"https://quvu.co.uk/
    c:"https://smartcell.co.in/
    c:"https://www.stayaok.com/",
    c:"https://www.talkdesk.com/",
    c:"https://auth.tcn.com/",login?state=hKFo2SAyUDZSYWxiOE5zTEVmenhBSm16cnRvNms1VEFMNzYwLaFupWxvZ2luo3RpZNkgVll1OWg0UHRlQzJFVVJnbDlRdlVvVTdKaVpHZDFTWTGjY2lk2SBMaWU0NG9IZ3FSdVdNVzZjU3d5ZlQ2QTJFSXhwcThONQ&client=Lie44oHgqRuWMW6cSwyfT6A2EIxpq8N5&protocol=oauth2&prompt=login&response_type=id_token&redirect_uri=c:"https%3A%2F%2Foperator.tcn.com%",2F%3Floginref%3D&scope=openid%20email&nonce=k5CM1LUwiaomObwB4Zaz62E7Y4PPYUqb&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMS4zIn0%3D
    c:"https://telecrm.in/
    c:"https://www.vert-age.com/",
    c:"https://www.voicecti.com/",
    c:"https://voiptimecloud.com/",
    c:"https://voiptimecloud.com/",
    c:"https://linksquares.com/",
    c:"https://www.docusign.com/",products/insight
    c:"https://www.lexion.ai/
    c:"https://www.sirionlabs.com/",sirion-one/
    c:"https://www.evisort.com/",
    c:"https://www.intelagree.com/",
    c:"https://www.affinitext.com/",
    c:"https://www.malbek.io/product-contrax
    c:"https://conga.com/",
    c:"https://www.gatekeeperhq.com/",
    c:"https://www.icertis.com/",
    c:"https://www.logicalconstruct.com/",
    c:"https://www.akorda.com/",
    c:"https://www.cobblestonesoftware.com/",
    c:"https://www.onit.com/",products/onit-reviewai/
    c:"https://www.pramata.com/",
    c:"https://kirasystems.com/",
    c:"https://www.lexcheck.com/",
    c:"https://loio.com/",product
    c:"https://www.paperflip.com/",
    NA 
    c:"https://secure.ebrevia.com/",
    http://www.klarity-analytics.com/",
    c:"https://trackx.com/",
    c:"https://aavenir.com/",
    c:"https://www.blackboiler.com/",
    c:"https://www.brightleaf.com/",
    c:"https://www.highiq.ai/
    c:"https://www.cortical.io/
    c:"https://initiohq.com/",
    c:"https://www.legislate.tech/
    c:"https://www.edgeverve.com/",
    c:"https://www.onit.com/",products/onit-extractai/
    c:"https://www.ontra.ai/
    c:"https://thinkingmachines.in/
    c:"https://www.thoughttrace.com/",
    c:"https://uhurasolutions.com/",force-majeure/
    c:"https://zycusicontract.com/",
    c:"https://zuva.ai/docai/
    c:"https://linksquares.com/",
    c:"https://www.docusign.com/",products/clm
    c:"https://www.evisort.com/",
    c:"https://ironcladapp.com/",
    c:"https://conga.com/",products/manage-contracts
    c:"https://www.ariba.com/",
    c:"https://www.icertis.com/",
    c:"https://www.sirionlabs.com/",
    c:"https://juro.com/",
    c:"https://www.contractlogix.com/",
    c:"https://www.lexion.ai/
    c:"https://www.workday.com/",
    c:"https://www.cobblestonesoftware.com/",
    c:"https://www.gatekeeperhq.com/",
    c:"https://www.malbek.io/product-contrax
    c:"https://www.spotdraft.com/",
    c:"https://www.intelagree.com/",
    c:"https://dealhub.io/
    c:"https://www.oracle.com/",in/erp/procurement/
    c:"https://www.basware.com/",en-en/home/
    c:"https://www.agiloft.com/",
    c:"https://getoutlaw.com/",
    c:"https://www.concordnow.com/",
    c:"https://conga.com/",products/manage-contracts
    c:"https://www.edgeverve.com/",
    c:"https://www.contractworks.com/",
    c:"https://www.aodocs.com/",
    c:"https://contractbook.com/",
    c:"https://inhubber.com/",en/
    c:"https://www.summize.com/",
    c:"https://www.akorda.com/",
    c:"https://www.legito.in/
    c:"https://contractpodai.com/",
    c:"https://www.jaggaer.com/",
    c:"https://www.modeln.com/",tbd_products/clm/
    c:"https://onspring.com/",
    c:"https://www.precisely.com/",
    c:"https://simplicontract.com/",
    c:"https://www.zoho.com/",contracts/
    c:"https://aavenir.com/",
    c:"https://www.linklaters.com/",
    c:"https://www.zycus.com/",
    NA 
    c:"https://www.contracts365.com/",
    c:"https://www.medius.com/",
    c:"https://www.onit.com/",
    c:"https://www.opentext.com/",
    c:"https://zealdocs.org/
    c:"https://acquirell.com/",
    c:"https://www.arc-cm.co/
    c:"https://avokaado.io/
    c:"https://newgensoft.com/",
    c:"https://www.contractvaz.com/",
    c:"https://imanage.com/",partner-products/partner-product/?productId=585
    c:"https://www.ecteon.com/",
    http://www.initio.com/",
    http://www.i-qs.com/",
    c:"https://kohoconsulting.com/",
    c:"https://lighthub.law/
    c:"https://easymerlin.com/",
    c:"https://www.opensourceinc.com/",
    c:"https://www.optimusbt.com/",
    c:"https://omega365.com/",
    c:"https://www.ricago.com/",contracts-and-obligations-management-system/
    c:"https://smartcontractclm.com/",
    c:"https://technomile.com/",products/grc-suite/
    c:"https://ultria.com/",comp",any/contact/
    c:"https://smartcontractclm.com/",
    c:"https://www.volody.com/",
    c:"https://www.zoey.com/",
    c:"https://www.pandadoc.com/",
    c:"https://www.proposify.com/",
    c:"https://linksquares.com/",
    c:"https://www.accelo.com/",
    c:"https://dealhub.io/
    c:"https://www.getaccept.com/",
    c:"https://qwilr.com/",
    c:"https://www.evisort.com/",
    c:"https://juro.com/",
    c:"https://ironcladapp.com/",
    c:"https://www.docusign.com/",products/clm
    c:"https://www.hellobonsai.com/",
    c:"https://contractbook.com/",
    c:"https://www.lexion.ai/
    c:"https://www.contractworks.com/",
    c:"https://www.ariba.com/",
    c:"https://oneflow.com/",
    c:"https://www.getleeway.com/",
    c:"https://www.cobblestonesoftware.com/",
    c:"https://www.workday.com/",en-gb/products/spend-management/strategic-sourcing.html
    c:"https://www.spotdraft.com/",?utm_term=spotdraft&utm_campaign=Brand&utm_source=adwords&utm_medium=ppc&hsa_acc=5694103801&hsa_cam=16772238430&hsa_grp=141988398664&hsa_ad=596978525258&hsa_src=g&hsa_tgt=kwd-363778568866&hsa_kw=spotdraft&hsa_mt=p&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjw5ZSWBhCVARIsALERCvxN9x3ajJw5mJZT6VzRLEzfWFI5jxOmToCXZm_5_bK4XQvLCaRil8MaAi3cEALw_wcB
    c:"https://www.concordnow.com/",
    c:"https://www.sirionlabs.com/",sirion-one/
    c:"https://www.icertis.com/",
    c:"https://conga.com/",
    c:"https://www.affinitext.com/",
    c:"https://www.contractlogix.com/",
    c:"https://gogenuity.com/",
    c:"https://www.gatekeeperhq.com/",
    c:"https://www.revv.so/
    c:"https://www.contractsafe.com/",
    c:"https://www.malbek.io/product-contrax
    c:"https://conga.com/",products/conga-contract-intelligence
    c:"https://superokay.com/",
    c:"https://www.intelagree.com/",
    c:"https://inhubber.com/",en/
    c:"https://www.oracle.com/",in/erp/procurement/
    c:"https://parleypro.com/",
    c:"https://www.contracthero.de/
    c:"https://www.adobe.com/",in/
    c:"https://www.airslate.com/",
    c:"https://www.basware.com/",en-en/home/
    c:"https://www.pramata.com/",
    c:"https://www.agiloft.com/",solutions/contract-management-software/
    c:"https://conga.com/",
    c:"https://mitratech.com/",
    c:"https://comm",unity.sap.com/",topics/sourcing-and-contract-lifecycle-management
    c:"https://onspring.com/",
    c:"https://pocketlaw.com/",en-uk
    c:"https://www.akorda.com/",
    c:"https://www.contractzen.com/",
    c:"https://www.legito.in/
    c:"https://client.docsmore.com/",
    c:"https://www.emsigner.com/",
    c:"https://www.gep.com/",software/gep-smart
    c:"https://www.ivalua.com/",
    c:"https://www.ignitionapp.com/",
    c:"https://www.precisely.com/",
    c:"https://www.razor365.com/",
    c:"https://www.symfact.com/",
    c:"https://www.zapendo.com/",
    c:"https://www.modeln.com/",tbd_products/clm/
    c:"https://www.ariba.com/",
    c:"https://www.zycus.com/",solution/procurement-performance.html
    c:"https://www.agree.com/",
    c:"https://contractpodai.com/",
    c:"https://www.creatoriq.com/",
    c:"https://secure.ebrevia.com/",
    c:"https://www.jaggaer.com/",
    c:"https://www.easyvista.com/",
    c:"https://simplicontract.com/",
    c:"https://www.tradogram.com/",
    c:"https://uplevl.com/",
    c:"https://www.ascnet.com/",
    c:"https://axdraft.com/",
    c:"https://gobonfire.com/",
    NA 
    NA 
    c:"https://www.contracts365.com/",
    c:"https://www.coupa.com/",products/procurement
    c:"https://www.curtisfitch.com/",products/contracts/
    c:"https://esmsolutions.com/",contract-management/
    c:"https://www.exigent-group.com/",
    c:"https://www.expirationreminder.net/
    c:"https://apac.mediatrack.com.",au/Login.asp
    c:"https://www.medius.com/",
    c:"https://www.onit.com/",products/contract-lifecycle-management/
    c:"https://www.o
    c:"https://www.openwindows.com.",au/
    c:"https://www.procureport.com/",
    c:"https://www.riskrhino.com/",what-we-do/
    c:"https://corp.sertifi.com/",
    c:"https://www.sydle.com/",
    c:"https://www.trackado.com/",
    c:"https://www.trusthall.com/",
    c:"https://www.icontracts.com/",solutions/contract-management/
    c:"https://www.vortal.biz/
    c:"https://workrails.com/",
    c:"https://www.zealdocs.com/",
    c:"https://acquirell.com/",
    c:"https://www.acutenz.com/",index.html
    c:"https://adoptech.co.uk/
    c:"https://aerofiler.com/",
    c:"https://www.bigforktech.com/",
    c:"https://www.icgteam.com/",
    c:"https://arcprolite.com/",
    c:"https://www.arc-cm.co/
    c:"https://www.areusdev.com/",
    c:"https://www.ascnet.com/",
    c:"https://www.atamis.co.uk/contract-management-system
    http://www.avaima.com/",contract-management-software#.YsZpwXZBzrc
    c:"https://www.aveva.com/",en/products/contract-risk-management/
    c:"https://avvoka.com/",
    c:"https://www.axsar.com/",axsar-contracts/
    c:"https://www.bluetree.in/
    c:"https://borganised.brodies.com/",default.aspx
    c:"https://www.brightleaf.com/",
    c:"https://www.tqg.de/en/
    c:"https://www.clearx.io/
    c:"https://www.wolterskluwer.com/",
    c:"https://www.cmbi.com.",hk/en-US/softdown
    c:"https://cmxhub.com/",
    c:"https://www.cobblestonesoftware.com/",solutions/contract-management-software
    c:"https://www.comp",letecontractmanagement.com/",
    c:"https://www.houseofcontrol.com/",
    c:"https://conga.com/",products/machine-learning/conga-max
    c:"https://www.gordian.com/",
    c:"https://contractai.apporchid.com/",
    c:"https://www.contracteagle.com/",
    c:"https://www.contracthound.com/",
    c:"https://www.contractify.io/
    c:"https://www.intellect.com/",
    c:"https://www.contracthound.com/",
    c:"https://tueri.io/
    c:"https://www.hyperteam.com/",
    c:"https://www.contract.one/future
    c:"https://cequence.io/
    c:"https://www.contractpedia.com/",
    c:"https://contractsplus.koncordlaw.com/",
    c:"https://thecontrato.com/",en
    c:"https://www.contraxaware.com/",
    c:"https://www.convergepoint.com/",contract-management-software/
    NA 
    c:"https://www.docjuris.com/",
    c:"https://www.mydock365.com/",
    c:"https://www.mydock365.com/",
    c:"https://www.docketbook.com.",au/
    c:"https://secure.wordtech.com/",
    c:"https://doctract.com/",
    c:"https://dolphin-software.com/",
    c:"https://doc-process.com/",dxcontract/
    c:"https://dxc.com/",us/en
    c:"https://www.econtracthub.com/",
    c:"https://epiphanyinc.net/
    c:"https://www.ecteon.com/",
    http://www.objectorb.com/",
    c:"https://www.fabasoft.com/",en/products/fabasoft-contracts
    c:"https://firesideventures.com/",
    c:"https://www.fullstep.com/",en/
    c:"https://www.greatminds-software.com/",
    c:"https://www.heretik.com/",
    c:"https://www.igniteprocurement.com/",
    c:"https://weareindy.com/",
    c:"https://www.intelligentcontract.com/",en-us/
    c:"https://www.juridoc.com.",br/en/juridoc-the-1-all-in-one-contract-lifecycle-management-platform/
    c:"https://www.knowable.com/",essentials/
    c:"https://kohoconsulting.com/",
    c:"https://www.lexplosion.in/
    c:"https://www.lawgeex.com/",
    c:"https://www.light-hub.com/",
    c:"https://www.maxagreement.com/",
    c:"https://www.symplr.com/",
    c:"https://www.merlinbusinesssoftware.com/",
    NA 
    MochaDocs
    c:"https://monax.io/
    c:"https://www.novatusadvisory.com/",
    c:"https://noventia.fi/en/products/contract-management/
    c:"https://logicsource.com/",
    c:"https://www.opensourceinc.com/",
    c:"https://www.optimusbt.com/",
    c:"https://www.originsysglobal.com/",
    c:"https://www.otris.com/",
    c:"https://www.paperlessonline.com/",
    c:"https://www.papernest.com/",en/
    c:"https://papertracer.com/",
    c:"https://omega365.com/",
    c:"https://www.plainvanilla.co/
    c:"https://www.poseidoncm.com/",
    c:"https://craft.co/procuresafe-inc
    c:"https://www.quickfms.com/",contract-management-software
    http://www.tps-of-il.com/",
    c:"https://www.rosslyn.ai/
    c:"https://realyst.com/",realcontract/
    c:"https://reducer.co.uk/
    c:"https://revnue.com/",
    c:"https://www.ricago.com/",contracts-and-obligations-management-system/
    c:"https://sievo.com/",products/contract-analytics
    http://www.simplessus.com/",en/comp",any.html
    c:"https://www.simpleterms.co/
    c:"https://simplicontract.com/",
    c:"https://www.sports-decisions.com/",en/
    c:"https://www.sutisoft.com/",news-071214.html
    c:"https://technomile.com/",products/grc-suite/
    c:"https://www.tracpro.com/",
    c:"https://tractfile.com/",
    c:"https://ultria.com/",comp",any/about-us/
    c:"https://vendorful.com/",
    c:"https://v-finance.in/
    c:"https://www.volody.com/",contractmanagement
    c:"https://www.webcm.com.",au/
    c:"https://wemasoft.co.za/website/
    c:"https://zefort.com/",
    c:"https://www.zoey.com/",
    c:"https://people.ai/
    c:"https://www.gainsight.com/",
    c:"https://catalyst.io/
    c:"https://www.clari.com/",
    c:"https://www.planhat.com/",
    c:"https://www.demandfarm.com/",
    c:"https://www.clientsuccess.com/",
    c:"https://www.aviso.com/",
    c:"https://www.zomentum.com/",
    c:"https://customersuccessbox.com/",
    c:"https://prolifiq.ai/crush/
    c:"https://www.squivr.com/",
    c:"https://uplandsoftware.com/",altify/
    c:"https://kapta.com/",
    c:"https://www.recapped.io/
    c:"https://www.revegy.com/",
    c:"https://uplandsoftware.com/",roinnovation/
    c:"https://www.vitally.io/
    c:"https://www.totango.com/",?utm_source=google&utm_medium=cpc&utm_term=totango&utm_campaign=Branded&utm_content=a651f9ab-63a4-4eb4-bc7f-b6f8a229da98&gclid=CjwKCAjwiJqWBhBdEiwAtESPaG7DoKdZ9IA-6hBjVfbh7grLSM88Ru4Tzx0TIrzP-g5iwgSnpZ7a-xoCtpcQAvD_BwE
    c:"https://kizen.com/",
    c:"https://ambition.com/",
    c:"https://www.brainbase.com/",
    c:"https://buyerassist.io/
    c:"https://www.cerebriai.com/",grid_items/cerebri-ai%E2%80%AFlaunches-cerebri-values-cx-v2-platform
    c:"https://customergauge.com/",
    c:"https://www.dealpadapp.co.uk/
    c:"https://forecastable.com/",
    c:"https://metacx.com/",
    c:"https://prolifiq.ai/ace/
    c:"https://www.salesoptimizer.com/",
    c:"https://uplandsoftware.com/",kapost/
    c:"https://www.docusign.com/",en-in/
    c:"https://www.hellosign.com/",
    c:"https://www.pandadoc.com/",
    c:"https://www.signnow.com/",
    c:"https://www.foxit.com/",pdf-editor/
    c:"https://www.foxit.com/",esign-pdf/
    c:"https://eversign.com/",
    c:"https://www.pdffiller.com/",?mode=view
    c:"https://signrequest.com/",#/
    c:"https://www.adobe.com/",in/sign/free-trial-global.html?cmpgn=sem_standalone&sdid=L3XTTS6W&mv=search&ef_id=CjwKCAjwiJqWBhBdEiwAtESPaGc8HouDjNX2fmIflgbjoDp-XsFcNNNwLM3igZ3DkdFmf6N_XbZL4hoCJNkQAvD_BwE:G:s&s_kwcid=AL!3085!3!600935114041!e!!g!!adobe%20e%20sign&gclid=CjwKCAjwiJqWBhBdEiwAtESPaGc8HouDjNX2fmIflgbjoDp-XsFcNNNwLM3igZ3DkdFmf6N_XbZL4hoCJNkQAvD_BwE
    c:"https://www.proposify.com/",
    c:"https://www.lightico.com/",
    c:"https://www.formstack.com/",products/sign
    c:"https://www.getaccept.com/",
    c:"https://signeasy.com/",
    c:"https://www.adobe.com/",in/acrobat/comp",lete-pdf-solution.html?ttid=annual-pro&sdid=JZBJVWT6&mv=search&ef_id=CjwKCAjwiJqWBhBdEiwAtESPaIvQchrpKAYKt6ADOOZ-UEGhSd0omNTYtankDYreaoScP9i7wgP97RoCMYwQAvD_BwE:G:s&s_kwcid=AL!3085!3!600935055982!e!!g!!adobe%20acrobat&gclid=CjwKCAjwiJqWBhBdEiwAtESPaIvQchrpKAYKt6ADOOZ-UEGhSd0omNTYtankDYreaoScP9i7wgP97RoCMYwQAvD_BwE
    c:"https://cocosign.com/",?fpr=sergei83
    c:"https://rsign.com/",
    c:"https://www.onespan.com/",products/electronic-signature
    c:"https://www.gonitro.com/",
    c:"https://rmail.com/",
    c:"https://www.docsend.com/",
    c:"https://yousign.com/",
    c:"https://qwilr.com/",
    c:"https://www.thanksroger.com/",
    c:"https://www.scrive.com/",
    c:"https://www.cincel.digital/
    c:"https://www.box.com/",home
    c:"https://www.yotisign.com/",app/account/login
    c:"https://legalesign.com/",
    c:"https://www.dotloop.com/",
    c:"https://contractbook.com/",
    c:"https://www.dottedsign.com/",
    c:"https://www.zoho.com/",sign/
    c:"https://juro.com/",
    c:"https://setshape.com/",
    c:"https://corp.sertifi.com/",
    c:"https://oneflow.com/",
    c:"https://www.docverify.com/",
    c:"https://signaturely.com/",?fpr=hugo80
    c:"https://www.signaturit.com/",
    c:"https://signonthego.us/
    c:"https://www.revv.so/
    c:"https://www.signwell.com/",
    c:"https://www.e-sign.co.uk/
    c:"https://home.bluesnap.com/",accounts-receivable-automation/
    c:"https://www.validsign.eu/
    c:"https://rightsignature.com/",
    c:"https://www.concordnow.com/",
    c:"https://dochub.com/",?gclid=CjwKCAjwiJqWBhBdEiwAtESPaIwCUxXvejXmtbBxutmJAdSvaRw1wKu0CuJ4m5tvd8k_tt2Pgp5_ExoCU4YQAvD_BwE
    c:"https://www.gatekeeperhq.com/",
    c:"https://www.waiverforever.com/",
    c:"https://www.getleeway.com/",
    c:"https://www.signable.co.uk/
    c:"https://conga.com/",products/esignature/conga-sign
    c:"https://www.signority.com/",
    c:"https://www.securedsigning.co
    c:"https://msbdocs.com/",
    c:"https://www.waiverelectronic.com/",
    c:"https://www.airslate.com/",
    c:"https://skribbl.io/
    c:"https://www.signinghub.com/",
    c:"https://mydocsafe.com/",
    c:"https://www.smartwaiver.com/",
    c:"https://www.digisigner.com/",
    c:"https://www.pdffiller.com/",en/categories/pdf-sign&seal.htm
    c:"https://www.yozons.com/",
    c:"https://www.nintex.com/",
    c:"https://client.docsmore.com/",
    c:"https://sign.keepsolid.com/",
    c:"https://formswift.com/",
    c:"https://www.docufirst.com/",
    c:"https://www.emsigner.com/",
    c:"https://cocodoc.com/",
    c:"https://connective.eu/
    c:"https://www.softdocs.com/",etrieve
    c:"https://pdfpen.com/",pdfpen/
    c:"https://www.agrello.io/
    c:"https://inhubber.com/",en/
    c:"https://www.gonitro.com/",sign
    c:"https://www.alphatrust.com/",?hsLang=en
    c:"https://www.foxit.com/",
    c:"https://www.isignnow.com/",
    c:"https://www.msign.io/
    c:"https://www.smartsign.com/",
    c:"https://www.approveme.com/",
    c:"https://www.securedsigning.com/",
    c:"https://www.contractzen.com/",
    c:"https://www.esignly.com/",
    c:"https://www.getbusyplc.com/",
    c:"https://www.esignanywhere.net/en/
    c:"https://www.virtualcabinet.com/",
    c:"https://www.zapendo.com/",
    c:"https://www.boldsign.com/",
    c:"https://www.encyro.com/",
    c:"https://www.k2c.com/",
    c:"https://support.ignitionapp.com/",en/
    NA 
    c:"https://www.pdfautosigner.com/",
    c:"https://www.contracthero.de/
    c:"https://gleanview.com/",gleanquote
    c:"https://www.identrust.com/",
    c:"https://www.precisely.com/",
    c:"https://www.recordminder.com/",
    http://www.signashare.com/",login
    c:"https://www.signix.com/",
    c:"https://www.waiverfile.com/",
    c:"https://in.wesign.com/",
    c:"https://anvil.works/
    c:"https://assently.com/",e-sign/
    c:"https://blueink.com/",
    c:"https://www.connectwise.com/",
    c:"https://constellation1.com/",
    http://ww38.documentconnex.com/",
    c:"https://www.easysend.io/
    c:"https://emailsignaturerescue.com/",
    c:"https://gennet.com/",
    c:"https://www.filesdna.com/",
    c:"https://www.virtualcabinet.com/",
    c:"https://jiosign.jio.com/",home
    c:"https://www.opentext.com/",
    c:"https://otterwaiver.com/",
    c:"https://www.pdftron.com/",
    c:"https://penneo.com/",
    c:"https://sign.cc/
    c:"https://signmee-home.meesys.com/",
    c:"https://www.signnow.com/",
    c:"https://www.sutisoft.com/",e-signature-software/
    c:"https://syngrafii.com/",
    c:"https://www.zorrosign.com/",category/esignature/
    c:"https://www.ascertia.com/",
    c:"https://autenti.com/",pl/
    NA 
    c:"https://www.countasign.com/",
    c:"https://www.cygnature.io/
    c:"https://www.eoriginal.com/",customer-service-portal/
    c:"https://wesign.com/",
    c:"https://www.esignsystems.com/",
    c:"https://finger-ink.com/",
    c:"https://docspring.com/",
    c:"https://www.fusesign.com/",
    c:"https://www.pdffiller.com/",en/functionality/ifill-pdf-limit.htm
    c:"https://www.kofax.com/",products/signdoc
    c:"https://www.leegality.com/",
    c:"https://www.liveoak.net/
    c:"https://www.manchtech.com/",esign/
    c:"https://www.odoo.com/",app/sign
    c:"https://www.forcs.com/",
    c:"https://www.dropbox.com/",
    c:"https://www.quoter.com/",
    c:"https://www.reachhq.com/",static/closure.html
    c:"https://recyclerguard.com/",
    c:"https://www2.seamlessdocs.com/",ng/404
    c:"https://www.signbox.co.uk/
    c:"https://www.signcenter.com/",
    c:"https://www.signicat.com/",products/electronic-signatures
    c:"https://www.signix.com/",
    c:"https://www.signtech.com/",
    c:"https://topazsystems.com/",software.html
    c:"https://simplesign.io/
    c:"https://newsmartsafe.com/",
    c:"https://cpl.thalesgroup.com/",
    c:"https://truecopy.in/
    c:"https://www.usdgo
    NA 
    c:"https://www.vasion.com/",
    c:"https://www.vizolution.com/",
    c:"https://www.wesign.com/",
    NA 
    c:"https://www.4identity.eu/home.php
    c:"https://agreementexpress.com/",
    c:"https://arcsign.in/
    fautosigner.com
    ",c:"https://wp.awaiver.com/",
    c:"https://www.biometricagreement.com/",
    c:"https://blocknify.com/",
    c:"https://www.bottomline.com/",us
    c:"https://www.axicos.com/",
    c:"https://ceropapel.mx/
    c:"https://www.certinal.com/",
    c:"https://citygro.com/",
    c:"https://cloudsignatureconsortium.org/
    c:"https://www.cm.com/",en-in/sign/
    c:"https://www.cobblestonesoftware.com/",
    c:"https://www.symtrax.com/",
    c:"https://consultantsinabox.com/",
    c:"https://www.contraxaware.com/",
    c:"https://customertimes.com/",
    c:"https://www.digio.in/?gclid=Cj0KCQjw8amWBhCYARIsADqZJoWWt68Rcb7mkrUWGBEoLzxri3xp78fk5jw651C6XZHJPHmSPT727cwaAr5kEALw_wcB#/index
    c:"https://www.vizolution.com/",
    c:"https://www.docufree.com/",
    c:"https://documentesign.com/",
    c:"https://drysign.exelatech.in/
    c:"https://www.ensoftc.com/",
    c:"https://www.wolterskluwer.com/",en/solutions/eoriginal
    c:"https://www.emsigner.com/",Areas/Home/contracts
    c:"https://www.esigns.com/",
    c:"https://esigntoday.com/",
    c:"https://www.ethsign.xyz/
    c:"https://filesignatures.net/index.php?page=all
    c:"https://finger-ink.com/",
    c:"https://beesigned.com
    ",c:"https://getsig.com/",
    c:"https://globaltrustedsign.com/",
    c:"https://www.gosigner.com/",
    c:"https://www.identity.tm/gb/products/esign.html
    c:"https://www.idsignca.com/",
    c:"https://ink.it/
    c:"https://appfoundry.genesys.com/",
    c:"https://www.iwelcome",.com/",iwelcome",-mobile-identity
    c:"https://www.k2c.com/",
    c:"https://keyp.io/
    c:"https://www.mifiel.com/",es/
    c:"https://www.mmsonline.com/",suppliers/browse/paperless-parts
    c:"https://www.notarize.com/",
    c:"https://www.odysseytec.com/",esign/
    c:"https://okdokument.com/",sk/
    http://www.datasistemasweb.com/",
    c:"https://www.ontask.io/
    NA 
    c:"https://www.recro-net.com/",
    c:"https://orisys.com/",
    c:"https://www.oodrive.com/",
    c:"https://p7s-signer.software.informer.com/",
    c:"https://www.penpowerinc.com/",Electronic-Signature.asp
    c:"https://pleasesign.com.",au/
    c:"https://www.easyvista.com/",
    c:"https://www.readysign.com/",
    c:"https://www.realystsignatures.com/",
    c:"https://www.rntrust.ae/products/spitrust
    c:"https://www.sap.com/",india/products/electronic-signature-management.html
    c:"https://www.esign.selfiesign.co/
    c:"https://www.signatureconfirm.com/",
    c:"https://www.sign.co/
    c:"https://www.signeato.com/",
    c:"https://www.signhost.com/",
    c:"https://www.signiflow.com/",
    c:"https://www.signnow.com/",developers
    c:"https://www.signnow.com/",features/signoff-archiving-roi
    c:"https://www.signondoc.com/",
    c:"https://signrobo.com/",
    c:"https://www.signserver.org/
    c:"https://signulu.com/",
    c:"https://speedywaiver.io/
    c:"https://sproof.io/
    c:"https://www.stiply.com/",
    NA 
    c:"https://store.outrightcrm.com/",product/suitecrm-docusign-connector/#:~:text=DocuSign%20Connector%20is%20a%20faster,as%20you%20always%20be%20updated.
    c:"https://swiftcrm.com/",
    c:"https://www.tecalis.com/",products/electronic-signature
    c:"https://tegoly.com/",news/?lang=en
    c:"https://www.trappco.co.uk/
    c:"https://truecopy.in/truesignerdsc.html
    c:"https://twala.io/
    c:"https://ultradocuments.com/",esignature.aspx?signup
    c:"https://www.universign.com/",en/
    c:"https://usefulpdf.com/",
    c:"https://www.veri5digital.com/",post/what-is-digital-signature-and-how-does-it-work
    c:"https://veridocsign.com/",
    c:"https://www.validatedid.com/",vidsigner
    c:"https://wsign.cloud/
    c:"https://www.zenoo.com/",
    c:"https://zix.com/",products/email-message-privacy
    c:"https://www.zoey.com/",
    c:"https://www.badgermapping.com/",
    c:"https://spotio.com/",
    c:"https://salesrabbit.com/",
    c:"https://skynamo.com/",
    c:"https://www.leadsquared.com/",mobile-crm/
    c:"https://www.geopointe.com/",
    c:"https://mapmycustomers.me/
    c:"https://www.salesforceben.com/",
    c:"https://veloxy.io/
    c:"https://www.repsly.com/",
    c:"https://georep.com/",
    c:"https://www.pepperi.com/",
    c:"https://www.espatial.com/",
    c:"https://www.pitcher.com/",
    c:"https://promomash.com/",
    c:"https://www.mapview.com/",
    c:"https://beatroute.io/
    c:"https://www.forcemanager.com/",
    c:"https://repzo.com/",
    c:"https://salesdiary.in/
    c:"https://twib.online/
    c:"https://www.getassistive.com/",
    c:"https://www.deltasalesapp.com/",
    c:"https://www.caliper.com/",maptovu.htm
    c:"https://dynamics.microsoft.com/",en-in/
    c:"https://salesql.com/",?via=adk34
    c:"https://www.springglobal.com/",
    c:"https://mapline.com/",
    c:"https://www.opendoorlogistics.com/",
    c:"https://www.outfieldapp.com/",
    c:"https://www.resco.net/
    c:"https://brandscopic.com/",
    c:"https://www.feetport.com/",
    c:"https://app.fieldforceconnect.com/",auth/login
    c:"https://www.teamhaven.com/",
    c:"https://www.allgeo.com/",
    NA 
    c:"https://www.fieldassist.in/
    c:"https://www.form.com/",use-case/merchandising-software-solutions/
    c:"https://www.geosales.com.",br/
    c:"https://www.inzant.com.",au/
    c:"https://www.mapadore.com/",
    c:"https://www.octopuspro.com/",
    c:"https://pobuca.com/",
    c:"https://www.portatour.com/",en
    c:"https://www.routzy.com/",
    c:"https://salesrep.ai/
    c:"https://telenotes.com/",
    c:"https://www.mobilesalesforceautomation.net/
    19thmile.com
    ",c:"https://www.2020rdi.com/",
    c:"https://www.actsoft.com/",
    c:"https://www.aforza.com/",
    c:"https://www.axtria.com/",cloud-products/axtria-salesiq-sales-management-sales-planning-and-operations/
    c:"https://callproof.com/",
    c:"https://www.canvasmaster.net/
    c:"https://www.hugedomains.com/",
    http://cerrebro.com/",
    c:"https://www.coma",rch.com/",
    c:"https://www.coma",rch.com/",trade-and-services/data-management/online-distribution/mobile-sales-force/
    c:"https://www.custella.com/",
    NA 
    c:"https://www.doortodoorcrm.com/",
    c:"https://ekmob.com/",
    c:"https://www.encoregroup.aero/
    c:"https://www.engagia.com/",
    c:"https://www.evozard.com/",field-force-automation
    c:"https://briggsandwalker.com/",
    c:"https://www.fieldmax.in/
    c:"https://www.fieldpie.com/",
    c:"https://fieldproapp.com/",
    NA 
    c:"https://dan.com/",
    c:"https://www.dtonic.io/
    c:"https://www.grayfos.com/",
    c:"https://moonshadowmobile.com/",
    c:"https://growmaxbi.com/",
    c:"https://www.happisales.com/",
    NA 
    c:"https://happsales.com/",
    c:"https://www.imprintai.us/
    c:"https://www.insitusales.com/",en/
    c:"https://www.i-snapshot.com/",
    c:"https://www.jlanmobile.com/",
    http://knockwise.com/",
    c:"https://knoq.com/",
    c:"https://leadplotter.com/",
    c:"https://www.lystloc.com/",
    c:"https://mapseemaps.com/",
    c:"https://www.merlinmetrics.com/",
    c:"https://aspin.co.uk/
    c:"https://www.mobiantsolutions.com/",
    mobilesop.com
    ",c:"https://www.mobilrut.com/",
    c:"https://www.mobiwork.com/",
    c:"https://msalesapp.com/",
    c:"https://multisystems.com/",our-solutions/multiroute-app/
    c:"https://www.nomalys.com/",en/
    c:"https://www.onecomm",erce.group/
    c:"https://www.onsightapp.com/",
    c:"https://ordershark.wordpress.com/",
    c:"https://ordrtakr.co/
    c:"https://www.organizer.com/",
    c:"https://paramantra.com/",
    c:"https://www.pepupsales.com/",
    c:"https://www.pepupsales.com/",
    c:"https://www.perenso.com/",
    c:"https://thepitchmaster.com/",
    c:"https://www.popcheckapp.com/",
    c:"https://www.ai2.com/",
    c:"https://purveyance.com.",au/purveyance/
    c:"https://intecinfonet.com/",
    c:"https://www.redshedtechnology.com/",
    c:"https://repzio.com/",
    c:"https://www.repzone.com/",
    c:"https://www.salesbuzz.com/",
    c:"https://salesninja.asia/
    c:"https://www.blue-alligator.com/",
    c:"https://www.salestrendz.com/",
    c:"https://www.salesworx.ae/
    c:"https://www.scrmpro.com/",
    NA 
    c:"https://www.simplifield.com/",
    c:"https://www.smartsales.asia/
    c:"https://www.sterison.com/",salesforce-automation-solution/
    NA 
    c:"https://www.uffizio.com/",
    c:"https://fieldd.co/
    http://www.turfwalker.com/",
    c:"https://www.xkzero.com/",mobile-comm",erce/
    c:"https://www.gorattle.com/",
    c:"https://www.ringcentral.com/",
    c:"https://textexpander.com/",
    c:"https://www.17hats.com/",
    c:"https://www.proteus.co/
    c:"https://www.theroishop.com/",
    c:"https://www.rocketnotes.com/",
    c:"https://mailivery.io/
    c:"https://www.momentum-software.com/",
    c:"https://www.sap.com/",
    c:"https://www.decisionlink.com/",
    NA 
    http://ecquire.com/",
    c:"https://www.passagetechnology.com/",
    c:"https://breezz.io/
    NA 
    c:"https://kalendar.ai/
    c:"https://www.neosight.ai/
    c:"https://www.dropcowboy.com/",
    c:"https://salestrackmobile.com/",
    c:"https://calleridreputation.com/",
    c:"https://conga.com/",products/business-process-automation/conga-x-author-excel
    c:"https://www.orecx.com/",
    c:"https://outstand.com/",
    c:"https://platformax.com/",
    c:"https://www.point-of-reference.com/",solutions/referenceedge/
    c:"https://www.slydeck.io/
    c:"https://www.xactlycorp.com/",solutions/strategic-sales-planning
    c:"https://elioplus.com/",
    NA 
    c:"https://www.phonevalidator.com/",
    http://prospectpredict.com/",
    c:"https://www.samsoftware.com/",sage-fast-order/
    c:"https://www.solidworks.com/",sites/default/files/2018-08/3DS-2018-SWK-Launch2019-DataSheet-Sell.pdf
    c:"https://ubersmith.com/",
    
    c:"https://www.niceactimize.com/",
    c:"https://callrecorder.skvalex.com/",get
    c:"https://getcardify.com/",
    c:"https://www.contactscience.com/",
    c:"https://www.i3corporation.in/development/crm-software.html
    c:"https://dreamservicesoftware.com/",
    c:"https://www.eloquant.com/",en/
    http://ww1.etoggler.com/",
    http://www.footprintsmd.com/",
    c:"https://linkedhub.io/
    http://ww1.mailswift.io/
    c:"https://www.merchantadvantage.com/",
    c:"https://precontacttool.com/",
    c:"https://qualifier.ai/
    NA 
    c:"https://www.salesforce.com/",in/form/sem/lead-management/?d=7013y000000ZpOqAAK&nc=7013y000002Z5FPAA0&utm_source=google&utm_medium=sem&utm_campaign=in_br_slobcon&utm_content=phrase_7013y000000zpoqaakbr-google-/sem/lead-management/&ef_id=CjwKCAjwt7SWBhAnEiwAx8ZLagM5DWDbpwoQO0i-f1L00HzyCL8NzTWUcYwRxuJdmnZE2QgzF16nkBoC8D0QAvD_BwE:G:s&s_kwcid=AL!4720!3!592749490536!p!!g!!sales%20force%20software&gclid=CjwKCAjwt7SWBhAnEiwAx8ZLagM5DWDbpwoQO0i-f1L00HzyCL8NzTWUcYwRxuJdmnZE2QgzF16nkBoC8D0QAvD_BwE
    NA 
    c:"https://www.sapstore.com/",solutions/99054/Geocoding-Directories
    c:"https://sparktoro.com/",tools/sparkscore
    http://www.triggerfox.com/",
    c:"https://www.trilogymktg.com/",
    c:"https://www.mediafly.com/",valuestory-demo/
    c:"https://vouchercart.com/",
    c:"https://zebrafi.com/",
    NA 
    c:"https://www.get1page.com/",
    c:"https://2viz.io/
    c:"https://ace-contact-manager.soft32.com/",
    c:"https://activewords.com/",
    c:"https://www.antideo.com/",
    c:"https://artofemails.com/",
    c:"https://comm",unity.spiceworks.com/",
    c:"https://barista-ai.com/",
    c:"https://cbn.profile-hub.com/",App/
    c:"https://performanceloyaltygroup.com/",
    c:"https://blazedesk.com/",employeeportal/users/login
    c:"https://www.businesssaathi.com/",
    c:"https://www.bytepaper.com/",
    c:"https://www.callcabinet.com/",
    c:"https://callcomm",ando.com/",
    c:"https://www.callcruncher.com/",
    c:"https://calldorado.com/",
    c:"https://www.sap.com/",india/acquired-brands/what-is-calliduscloud.html
    c:"https://www.sap.com/",
    c:"https://calln.com/",
    c:"https://www.dynametric.com/",
    c:"https://callyzer.co/
    NA 
    c:"https://www.cherrypiksoftware.com/",
    c:"https://www.cloud4j.com/",report-builder.html
    c:"https://hellooutbound.com/",
    c:"https://contactbase.net/
    NA 
    c:"https://wwk.com/",
    c:"https://www.copy2contact.com/",
    c:"https://www.crik-it.net/secure/Crik-IT%20Login%20Page.aspx?ReturnUrl=%2f
    c:"https://custerem.com/",
    c:"https://www.datajib.com/",
    c:"https://www.dealpoint.io/
    c:"https://dealtable.com/",
    c:"https://docotive.com/",
    NA 
    c:"https://www.ebestglobal.com/",
    http://www.efficientaddressbook.com/",business/
    c:"https://virtualvalue.com/",
    c:"https://www.egobooster.io/
    c:"https://www.eighty6software.com/",
    NA 
    c:"https://equinoxsoftwareservices.com/",
    c:"https://www.essent.com/",One.html
    c:"https://exitadviser.com/",
    c:"https://fairwai.com/",
    c:"https://shiprush.com/",
    http://firstx.ai/
    http://addressbook.gassoftwares.com/",
    NA 
    c:"https://www.headshed.com/",
    c:"https://helloreferrals.com/",
    c:"https://ibizpanel.com/",
    c:"https://implisense.com/",en
    c:"https://indirectsales.com/",
    c:"https://www.interactivecalculator.com/",
    c:"https://www.jivesystems.com/",
    NA 
    c:"https://www.kuala.com/",
    c:"https://www.kwikbiz.in/
    http://www.libertydata.net/
    c:"https://magefan.com/",magento2-convert-guest-to-customer#:~:text=Magento%202%20Guest%20to%20Customer%20is%20an%20extension%20that%20adds,on%20a%20guest%20order%20information.
    c:"https://www.maxcalling.com/",mobile-only.php
    http://www.excelsof.com/",
    c:"https://www.microbilt.com/",product/business-search
    c:"https://app.miplani.com/",
    c:"https://www.modeln.com/",products/rebate-management/
    c:"https://modigie.com/",
    NA 
    c:"https://nureply.com/",
    http://www.opticlose.com/",#/
    c:"https://opusviz.com/",
    http://www.opusviz.com/",dcsm.html
    c:"https://papersoftware.com/",contract-tools
    c:"https://ololu.com.",br/
    c:"https://www.pluckrapp.com/",
    NA 
    c:"https://www.quicklines.ai/
    c:"https://www.plauti.com/",
    c:"https://recycly.it/
    c:"https://www.repcard.com/",
    c:"https://www.aleran.com/",
    c:"https://www.rpms.com/",
    c:"https://www.rolustech.com/",
    c:"https://www.saashop.com/",
    c:"https://saasmantra.com/",
    c:"https://www.salesatwork.com/",
    c:"https://www.salesedi.com/",login
    c:"https://www.saleshunter.com/",
    c:"https://www.salesin.com/",
    c:"https://g2edge.com/",
    c:"https://salesmatrix.com/",products/swot/
    c:"https://www.sap.com/",india/products/convergent-mediation.html
    c:"https://www.sap.com/",india/products/entitlement-management.html
    c:"https://www.sap.com/",india/products/territory-and-quota.html
    c:"https://sarvius.com/",
    c:"https://www.screentag.mobi/
    c:"https://sellersonar.com/",
    c:"https://sharkfinesse.com/",
    c:"https://simpleem.com/",
    c:"https://simplesell.com/",
    c:"https://simplestimate.com/",
    c:"https://smiddle.com/",en/solutions/contact-center-solutions/crm-connector-for-siebel
    c:"https://www.viewsonic.com/",in/
    c:"https://spearfysh.com/",
    NA 
    http://styledge.in/
    c:"https://buildr.com/",
    c:"https://supercharge.io/
    c:"https://supplymover.com/",
    c:"https://www.swantide.com/",
    c:"https://www.syndtrak.com/",LogOn.aspx?ReturnUrl=%2f
    c:"https://talentview.co/
    c:"https://www.appjetty.com/",
    c:"https://www.toplyne.io/
    c:"https://www.trackgo.com/",
    c:"https://www.transformania.com/",
    c:"https://unitedmasters.com/",
    http://universalavenue.com/",
    c:"https://upmesh.io/sg?utm_source=google&utm_medium=cpc&utm_campaign=UPMESH_Search_Traffic&utm_term=upmesh&utm_campaign=Upmesh_Search_Traffic&utm_source=adwords&utm_medium=ppc&hsa_acc=4675249709&hsa_cam=15790439880&hsa_grp=127040487490&hsa_ad=573273514307&hsa_src=g&hsa_tgt=kwd-1578495973633&hsa_kw=upmesh&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=CjwKCAjw2rmWBhB4EiwAiJ0mtV4QzIZx1x-GPPStPoIaNK6xeQA0i7PiCGXOeEZFbIDVzo--UYRhvxoCjEgQAvD_BwE
    c:"https://www.vidfox.in/
    c:"https://voicelog.com/",
    c:"https://www.klazify.com/",
    c:"https://webspotter.io/
    c:"https://www.weexpand.co/
    c:"https://wemapsales.com/",
    NA 
    NA 
    c:"https://whistle.mobi/
    c:"https://www.workist.com/",en
    c:"https://www.xaaspricing.com/",
    c:"https://www.xperify.be/
    NA 
    c:"https://www.yiftee.com/",
    c:"https://www.zendirect.com/",
    c:"https://zoomia.org/en/
    c:"https://reveal.co/
    c:"https://impact.com/",
    c:"https://partnerstack.com/",
    c:"https://www.crossbeam.com/",
    c:"https://www.kiflo.com/",
    c:"https://partnertap.com/",
    c:"https://www.partnerportal.io/
    c:"https://www.partnerhub.app/
    c:"https://partnered.com/",
    c:"https://partnerize.com/",
    c:"https://www.mirakl.com/",
    c:"https://trackier.com/",
    c:"https://www.tune.com/",
    c:"https://www.gopronto.io/
    c:"https://www.workspan.com/",
    c:"https://breezy.io/
    c:"https://constellant.com/",site/global/home/index.gsp
    c:"https://www.cosell.io/
    c:"https://www.ingenioustechnologies.com/",
    c:"https://web.measurematch.com/",solutions/partnerexchange
    c:"https://www.moonshot.partners/
    c:"https://www.netcracker.com/",portfolio/solutions/digital-transformation-for-cable-providers/
    c:"https://paylode.com/",
    c:"https://www.spiisee.com/",
    c:"https://www.tidwit.com/",
    NA 
    c:"https://www.zomentum.com/",partneralign
    c:"https://impact.com/",
    c:"https://partnerstack.com/",
    c:"https://www.zinfi.com/",
    c:"https://impartner.com/",?gclid=CjwKCAjw2rmWBhB4EiwAiJ0mtag1WDgbjkKQzZVzCcbTxIlWHcoQpVjleXv5Dg46L4RmE6lWRxXFjBoClWcQAvD_BwE
    c:"https://ziftsolutions.com/",
    c:"https://www.allbound.com/",
    c:"https://www.everflow.io/
    c:"https://reveal.co/
    c:"https://oneaffiniti.com/",
    c:"https://www.partnerlinq.net/
    c:"https://partnertap.com/",
    c:"https://www.kiflo.com/",
    c:"https://www.crossbeam.com/",
    c:"https://affise.com/",
    c:"https://leadmethod.com/",
    c:"https://www.structuredweb.com/",
    c:"https://partnerize.com/",
    c:"https://www.magentrix.com/",prm
    c:"https://www.salesforce.com/",resources/articles/channel-sales-guide/
    c:"https://www.tune.com/",
    c:"https://www.cosell.io/
    c:"https://www.partnerportal.io/
    c:"https://www.vartopia.com/",
    c:"https://www.channeltivity.com/",
    c:"https://www.mindmatrix.net/
    c:"https://partnered.com/",
    c:"https://www.partnerhub.app/
    c:"https://www.getreditus.com/",
    c:"https://www.workspan.com/",
    c:"https://www.awin.com/",gb
    c:"https://www.oracle.com/",in/cx/sales/partner-relationship-management/
    c:"https://trackier.com/",
    c:"https://www.ibm.com/",products/partner-engagement-manager
    c:"https://qollabi.com/",
    c:"https://www.apideck.com/",products/ecosystem
    c:"https://comp",utermarketresearch.com/",partner-portal-articles/
    c:"https://spotsource.com/",
    NA 
    c:"https://www.partnerfleet.io/
    c:"https://www.pega.com/",?&utm_source=google&utm_medium=cpc&utm_campaign=G_India_Brand_Core_EN&utm_term=pega&gloc=1007765&utm_content=pcrid%7c483881453240%7cpkw%7ckwd-21203626%7cpmt%7cb%7cpdv%7cc%7c&gclid=CjwKCAjw_b6WBhAQEiwAp4HyINWKQlgoNyLiemVJviyjq_4PbgZWFa78cSciWAXCEgXYOcfyh8749RoCLWIQAvD_BwE&gclsrc=aw.ds
    c:"https://xamplify.com/",
    NA 
    c:"https://channelmechanics.com/",channel-partner-management/
    c:"https://gorillaict.com/",
    c:"https://myprm.com/",en/
    c:"https://p2pglobal.info/
    c:"https://agentcis.com/",
    c:"https://aidhound.com/",meet
    c:"https://www.allianceboard.com/",
    c:"https://www.balluun.com/",
    NA 
    c:"https://aichannels.app/
    NA 
    c:"https://www.channelkonnect.com/",
    c:"https://en.channelxperts.com/",channel-os/
    c:"https://en.channelxperts.com/",channel-os/
    c:"https://www.aximpro.com/",
    c:"https://channelyze.io/
    c:"https://conveyservices.com/",
    c:"https://www.gorillatoolz.com/",
    c:"https://www.elioplus.com/",channel-partner-recruitment
    c:"https://elioplus.com/",prm-software
    c:"https://vivun.com/",eval
    NA 
    c:"https://www.ibm.com/",in-en/supply-chain/collaboration
    c:"https://innosabi.com/",startup/
    c:"https://www.kademi.co/
    c:"https://www.logicbay.com/",
    c:"https://www.logicbay.com/",fuse
    c:"https://web.measurematch.com/",solutions/partnerexchange
    c:"https://www.netformx.com/",products/channelxpert/
    c:"https://www.onebillsoftware.com/",multi-level-channel-management/
    c:"https://www.optimisemedia.com/",products/native-advertising
    c:"https://www.optimisemedia.com/",products/native-advertising
    c:"https://www.partnerinsight.io/
    c:"https://www.subex.com/",
    NA 
    c:"https://www.prmdeals.com/",
    c:"https://www.saasquatch.com/",
    c:"https://www.scopeinc.com/",faq/expert-management-platform
    NA 
    NA 
    c:"https://trak.io/
    c:"https://trak.io/
    c:"https://www.vistex.com/",solutions-sap/
    c:"https://www.vistex.com/",cloud-solutions/
    c:"https://www.salesforce.com/",products/cpq/overview/
    c:"https://www.hubspot.com/",products/sales/get-started
    c:"https://dealhub.io/
    c:"https://www.pandadoc.com/",
    c:"https://www.paperlessparts.com/",
    c:"https://www.proposify.com/",
    c:"https://www.apparound.com/",
    c:"https://www.zoho.com/",in/crm/
    c:"https://www.configureone.com/",
    c:"https://www.oracle.com/",in/cx/sales/cpq/#:~:text=Oracle%20CPQ%20is%20a%20cloud,meet%20their%20customers'%20pricing%20needs.
    c:"https://www.salesforce.com/",solutions/industries/comm",unications/comm",unications-cloud/
    c:"https://qwilr.com/",
    c:"https://aq-fes.com/",
    c:"https://www.inmindcloud.com/",
    c:"https://www.expeditecomm",erce.com/",home
    c:"https://www.cloudsense.com/",
    c:"https://digifabster.com/",
    c:"https://home.bluesnap.com/",accounts-receivable-automation/
    c:"https://www.experlogix.com/",
    c:"https://fastspring.com/",interactive-quotes/
    c:"https://www.quoter.com/",
    c:"https://hivecpq.com/",en/
    c:"https://www.quotewerks.com/",
    c:"https://www.ibm.com/",products/configure-price-quote
    c:"https://vloxq.com/",en/
    c:"https://conga.com/",products/comm",erce/conga-cpq
    c:"https://www.epicor.com/",
    c:"https://www.vendavo.com/",
    c:"https://www.tacton.com/",
    c:"https://www.pricefx.com/",
    c:"https://www.connectwise.com/",platform/business-management/sell
    c:"https://www.xait.com/",xaitcpq
    c:"https://www.sap.com/",india/products/cpq.html
    c:"https://www.revv.so/quoting-software.html
    c:"https://servicepath.co/
    c:"https://pros.com/",products/cpq-software/
    c:"https://www.zuora.com/",products/cpq-software/
    c:"https://www.iquotexpress.com/",
    c:"https://www.axonom.com/",powertrak
    c:"https://www.bit2win.com/",
    c:"https://verenia.com/",
    c:"https://www.connectbase.com/",
    c:"https://www.zilliant.com/",
    c:"https://fpx.revalizesoftware.com/",
    c:"https://www.ezlynx.com/",
    c:"https://www.konfigear.com/",
    NA 
    NA 
    c:"https://configit.com/",configit-quote/
    c:"https://gleanview.com/",gleanquote
    c:"https://www.infor.com/",
    c:"https://orgzit.com/",
    http://www.qwikquote.com/",
    c:"https://www.saasteps.com/",
    c:"https://chikpea.com/",
    c:"https://www.mosspaper.com/",
    c:"https://www.revops.io/
    http://www.saleskit.co.in/
    c:"https://www.sofon.com/",en/
    c:"https://www.aicomp",.com/",
    c:"https://www.camos.de/en/
    c:"https://canvaslogic.de/en/
    c:"https://clarity-software.com/",
    c:"https://www.varstreetinc.com/",platform/b2b-sales-quoting
    c:"https://www.easasoftware.com/",
    c:"https://www.encoway.de/en/
    c:"https://erep.com/",
    c:"https://www.etiya.com/",en/products/configure-price-and-quote
    c:"https://magento.stackexchange.com/",questions/290102/how-the-magento-2-final-price-calculate-for-the-simple-product
    c:"https://www.modeln.com/",addons/cpq-for-sap/
    c:"https://www.netformx.com/",products/salesxpert/
    c:"https://www.rockwellautomation.com/",en-in/tools/myrockwellautomation/help-center/repairs.html
    c:"https://psquote.com/",
    c:"https://www.quoter.com/",
    c:"https://saleswon.com/",
    c:"https://www.chikpea.com/",
    c:"https://www.veloceapps.com/",
    c:"https://www.workbooks.com/",
    c:"https://workrails.com/",
    c:"https://cisconfigurator.com/",
    c:"https://www.guros.com/",
    c:"https://store.sap.com/",
    c:"https://www.combinum.com/",
    c:"https://www.contract-alert.com/",
    c:"https://cpqcart.com/",
    c:"https://www.cincom.com/",
    c:"https://www.cuberm.com/",
    c:"https://www.dextara.com/",
    c:"https://ebizplatform.hosting.pinbn.net/",
    c:"https://www.elfsquad.io/",
    c:"https://www.monetizenow.io/",
    c:"https://enxoo.com/",
    c:"https://www.gocloudz.com/",
    c:"https://www.channelcentral.net/",
    c:"https://intelliquip.com/",
    c:"https://itquoter.com/",
    c:"https://www.klarocpq.fi/en/",
    c:"https://www.lino.de/en/",
    c:"https://www.logik.io/",
    c:"https://www.itoris.com/",
    c:"https://www.masterstreamerp.com/",
    c:"https://quootz.eu/merkato/merkato-cpq/",
    c:"https://www.miclient.in/",
    c:"https://miraworks.io/comp",
    c:"https://mobileforcesoftware.com/",
    c:"https://www.modeln.com/",
    c:"https://www.mycloudpa.com/",
    c:"https://www.netformx.com/",
    c:"https://www.nue.io/",
    c:"https://www.onebillsoftware.com/",
    c:"https://www.onecpq.com/",
    c:"https://www.openpricer.com/",
    c:"https://www.osmoscloud.com/",
    c:"https://www.power-soft.com/",
    c:"https://www.proquote-solutions.com/",
    c:"https://qote.it/;,
    c:"https://quotebee.io/",
    c:"https://dsi.supplyframe.app/",
    c:"https://quoterobot.com/",
    c:"https://www.quoteroller.com/",
    c:"https://supplyframe.com/",
    c:"https://www.repcon.es/",
    c:"https://revalizesoftware.com/",
    c:"https://revalizesoftware.com/",
    c:"https://rightinformation.com/",
    c:"https://www.saleconfig.com/",
    c:"https://www.salesbricks.com/",
    c:"https://corspro.com/",
    c:"https://salesqueze.com/",
    c:"https://scopestack.io/services-cpq/",
    c:"https://twistellar.com/",
    c:"https://www.teamform.co/",
    c:"https://www.partfiniti.com/",
    c:"http://www.solidifyinc.com/",
    c:"https://stevetheclerk.com/",
    c:"https://www.subskribe.com/",
    c:"https://swiftcrm.com/",
    c:"https://synoptive.com/",
    c:"https://www.technicon.com/",
    c:"https://ignitetech.com/",
    c:"https://www.vistex.com/",
    c:"https://www.yagnaiq.com/",
    c:"https://zimit.io/",
    c:"https://prisync.com/",
    c:"https://www.price2spy.com/",
    c:"https://pros.com/",
    c:"https://www.quoter.com/",
    c:"https://www.omniaretail.com/",
    c:"https://www.pricefx.com/",
    c:"https://tgndata.com/",
    c:"https://www.wiser.com/",
    c:"https://competera.net/",
    c:"https://www.epicor.com/",
    c:"https://feedvisor.com/",
    c:"https://www.zilliant.com/",
    c:"https://www.blackcurve.com/",
    c:"https://www.vendavo.com/",
    c:"https://www.trackstreet.com/",
    c:"https://verenia.com/",
    c:"https://get.responsibid.com/",
    c:"https://priceedge.eu/
    c:"https://www.inmindcloud.com/",
    c:"https://www.intelligencenode.com/",
    c:"https://brainleaf.com/",
    c:"https://www.demandtec.com/",
    
    c:"https://www.quicklizard.com/",
    c:"https://www.repricerexpress.com/",
    c:"https://www.propricer.com/",
    NA 
    c:"https://www.vistaar.com/",
    c:"https://www.buynomics.com/",
    c:"https://chikpea.com/",
    NA 
    c:"https://www.syncron.com/",
    c:"https://www.cuberm.com/",
    c:"https://www.darwinpricing.com/",
    c:"https://www.easasoftware.com/",
    c:"https://intelisale.com/",
    c:"https://www.modeln.com/",
    c:"https://www.netformx.com/",
    c:"https://pricetweakers.net/
    c:"https://www.saphran.com/",
    c:"https://cleardemand.com/",
    c:"https://revionics.com/",
    c:"https://workrails.com/",
    c:"https://www.bqool.com/",
    c:"https://advancedpricinglogic.com/",
    c:"https://www.ahimsacloud.com/",
    c:"https://alihunter.io/",
    c:"https://alpharepricer.com/",
    c:"https://www.anybigdata.com/",
    c:"https://advancedpricinglogic.com/",
    c:"https://www.revenueanalytics.com/",
    c:"https://www.boardfy.com/",
    c:"https://www.sposea.com/",
    c:"https://www.bubo.ai/",
    c:"https://cleard3.com/",
    c:"https://competitoor.com/",
    c:"https://www.comp",ete.ai/
    c:"https://www.ctrlio.com/",
    c:"https://dealavo.com/",
    c:"https://www.digonex.com/",
    c:"https://www.engage3.com/",
    c:"https://success-systems.com/",
    c:"https://www.epriceanalysis.com/",

    c:"https://getrealprice.com/",
    c:"https://www.goalprofit.com/",
    c:"https://go-pricing.com/",
    c:"https://growbydata.com/",
    c:"https://helecos.com/",
    c:"https://imprice.ai/
    c:"https://www.increff.com/",
    c:"https://paganresearch.io/comp",
    c:"https://innoveo.com/",
    c:"https://www.insitetrack.com/",
    c:"https://www.kaizenanalytix.com/",
    c:"https://www.keremi.com/",
    c:"https://konigle.com/",
    c:"https://www.brandbucket.com/",
    c:"https://www.methodosit.com.",
    c:"https://www.minderest.com/",
    c:"https://windocks.com/",
    c:"https://optimusprice.ai/
    c:"https://paarly.com/",
    c:"https://www.paritydeals.com/",
  

}*/